// Code generated by ent, DO NOT EDIT.

package registration

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the registration type in the database.
	Label = "registration"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldGameID holds the string denoting the game_id field in the database.
	FieldGameID = "game_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldNameNormalized holds the string denoting the name_normalized field in the database.
	FieldNameNormalized = "name_normalized"
	// FieldSecretHash holds the string denoting the secret_hash field in the database.
	FieldSecretHash = "secret_hash"
	// FieldViaSharedDevice holds the string denoting the via_shared_device field in the database.
	FieldViaSharedDevice = "via_shared_device"
	// FieldLeftNeighborID holds the string denoting the left_neighbor_id field in the database.
	FieldLeftNeighborID = "left_neighbor_id"
	// FieldRightNeighborID holds the string denoting the right_neighbor_id field in the database.
	FieldRightNeighborID = "right_neighbor_id"
	// FieldAssignedRoleID holds the string denoting the assigned_role_id field in the database.
	FieldAssignedRoleID = "assigned_role_id"
	// EdgeGame holds the string denoting the game edge name in mutations.
	EdgeGame = "game"
	// Table holds the table name of the registration in the database.
	Table = "registrations"
	// GameTable is the table that holds the game relation/edge.
	GameTable = "registrations"
	// GameInverseTable is the table name for the Game entity.
	// It exists in this package in order to avoid circular dependency with the "game" package.
	GameInverseTable = "games"
	// GameColumn is the table column denoting the game relation/edge.
	GameColumn = "game_id"
)

// Columns holds all SQL columns for registration fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldGameID,
	FieldName,
	FieldNameNormalized,
	FieldSecretHash,
	FieldViaSharedDevice,
	FieldLeftNeighborID,
	FieldRightNeighborID,
	FieldAssignedRoleID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// NameNormalizedValidator is a validator for the "name_normalized" field. It is called by the builders before save.
	NameNormalizedValidator func(string) error
	// SecretHashValidator is a validator for the "secret_hash" field. It is called by the builders before save.
	SecretHashValidator func(string) error
	// DefaultViaSharedDevice holds the default value on creation for the "via_shared_device" field.
	DefaultViaSharedDevice bool
)

// OrderOption defines the ordering options for the Registration queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByGameID orders the results by the game_id field.
func ByGameID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGameID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByNameNormalized orders the results by the name_normalized field.
func ByNameNormalized(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNameNormalized, opts...).ToFunc()
}

// BySecretHash orders the results by the secret_hash field.
func BySecretHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSecretHash, opts...).ToFunc()
}

// ByViaSharedDevice orders the results by the via_shared_device field.
func ByViaSharedDevice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldViaSharedDevice, opts...).ToFunc()
}

// ByLeftNeighborID orders the results by the left_neighbor_id field.
func ByLeftNeighborID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLeftNeighborID, opts...).ToFunc()
}

// ByRightNeighborID orders the results by the right_neighbor_id field.
func ByRightNeighborID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRightNeighborID, opts...).ToFunc()
}

// ByAssignedRoleID orders the results by the assigned_role_id field.
func ByAssignedRoleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAssignedRoleID, opts...).ToFunc()
}

// ByGameField orders the results by game field.
func ByGameField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGameStep(), sql.OrderByField(field, opts...))
	}
}
func newGameStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GameInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GameTable, GameColumn),
	)
}
