// Code generated by ent, DO NOT EDIT.

package registration

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/loomi-labs/clockkeeper/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Registration {
	return predicate.Registration(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Registration {
	return predicate.Registration(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Registration {
	return predicate.Registration(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Registration {
	return predicate.Registration(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Registration {
	return predicate.Registration(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Registration {
	return predicate.Registration(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Registration {
	return predicate.Registration(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Registration {
	return predicate.Registration(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Registration {
	return predicate.Registration(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Registration {
	return predicate.Registration(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Registration {
	return predicate.Registration(sql.FieldEQ(FieldUpdatedAt, v))
}

// GameID applies equality check predicate on the "game_id" field. It's identical to GameIDEQ.
func GameID(v int) predicate.Registration {
	return predicate.Registration(sql.FieldEQ(FieldGameID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Registration {
	return predicate.Registration(sql.FieldEQ(FieldName, v))
}

// NameNormalized applies equality check predicate on the "name_normalized" field. It's identical to NameNormalizedEQ.
func NameNormalized(v string) predicate.Registration {
	return predicate.Registration(sql.FieldEQ(FieldNameNormalized, v))
}

// SecretHash applies equality check predicate on the "secret_hash" field. It's identical to SecretHashEQ.
func SecretHash(v string) predicate.Registration {
	return predicate.Registration(sql.FieldEQ(FieldSecretHash, v))
}

// ViaSharedDevice applies equality check predicate on the "via_shared_device" field. It's identical to ViaSharedDeviceEQ.
func ViaSharedDevice(v bool) predicate.Registration {
	return predicate.Registration(sql.FieldEQ(FieldViaSharedDevice, v))
}

// LeftNeighborID applies equality check predicate on the "left_neighbor_id" field. It's identical to LeftNeighborIDEQ.
func LeftNeighborID(v int) predicate.Registration {
	return predicate.Registration(sql.FieldEQ(FieldLeftNeighborID, v))
}

// RightNeighborID applies equality check predicate on the "right_neighbor_id" field. It's identical to RightNeighborIDEQ.
func RightNeighborID(v int) predicate.Registration {
	return predicate.Registration(sql.FieldEQ(FieldRightNeighborID, v))
}

// AssignedRoleID applies equality check predicate on the "assigned_role_id" field. It's identical to AssignedRoleIDEQ.
func AssignedRoleID(v string) predicate.Registration {
	return predicate.Registration(sql.FieldEQ(FieldAssignedRoleID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Registration {
	return predicate.Registration(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Registration {
	return predicate.Registration(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Registration {
	return predicate.Registration(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Registration {
	return predicate.Registration(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Registration {
	return predicate.Registration(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Registration {
	return predicate.Registration(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Registration {
	return predicate.Registration(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Registration {
	return predicate.Registration(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Registration {
	return predicate.Registration(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Registration {
	return predicate.Registration(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Registration {
	return predicate.Registration(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Registration {
	return predicate.Registration(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Registration {
	return predicate.Registration(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Registration {
	return predicate.Registration(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Registration {
	return predicate.Registration(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Registration {
	return predicate.Registration(sql.FieldLTE(FieldUpdatedAt, v))
}

// GameIDEQ applies the EQ predicate on the "game_id" field.
func GameIDEQ(v int) predicate.Registration {
	return predicate.Registration(sql.FieldEQ(FieldGameID, v))
}

// GameIDNEQ applies the NEQ predicate on the "game_id" field.
func GameIDNEQ(v int) predicate.Registration {
	return predicate.Registration(sql.FieldNEQ(FieldGameID, v))
}

// GameIDIn applies the In predicate on the "game_id" field.
func GameIDIn(vs ...int) predicate.Registration {
	return predicate.Registration(sql.FieldIn(FieldGameID, vs...))
}

// GameIDNotIn applies the NotIn predicate on the "game_id" field.
func GameIDNotIn(vs ...int) predicate.Registration {
	return predicate.Registration(sql.FieldNotIn(FieldGameID, vs...))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Registration {
	return predicate.Registration(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Registration {
	return predicate.Registration(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Registration {
	return predicate.Registration(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Registration {
	return predicate.Registration(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Registration {
	return predicate.Registration(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Registration {
	return predicate.Registration(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Registration {
	return predicate.Registration(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Registration {
	return predicate.Registration(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Registration {
	return predicate.Registration(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Registration {
	return predicate.Registration(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Registration {
	return predicate.Registration(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Registration {
	return predicate.Registration(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Registration {
	return predicate.Registration(sql.FieldContainsFold(FieldName, v))
}

// NameNormalizedEQ applies the EQ predicate on the "name_normalized" field.
func NameNormalizedEQ(v string) predicate.Registration {
	return predicate.Registration(sql.FieldEQ(FieldNameNormalized, v))
}

// NameNormalizedNEQ applies the NEQ predicate on the "name_normalized" field.
func NameNormalizedNEQ(v string) predicate.Registration {
	return predicate.Registration(sql.FieldNEQ(FieldNameNormalized, v))
}

// NameNormalizedIn applies the In predicate on the "name_normalized" field.
func NameNormalizedIn(vs ...string) predicate.Registration {
	return predicate.Registration(sql.FieldIn(FieldNameNormalized, vs...))
}

// NameNormalizedNotIn applies the NotIn predicate on the "name_normalized" field.
func NameNormalizedNotIn(vs ...string) predicate.Registration {
	return predicate.Registration(sql.FieldNotIn(FieldNameNormalized, vs...))
}

// NameNormalizedGT applies the GT predicate on the "name_normalized" field.
func NameNormalizedGT(v string) predicate.Registration {
	return predicate.Registration(sql.FieldGT(FieldNameNormalized, v))
}

// NameNormalizedGTE applies the GTE predicate on the "name_normalized" field.
func NameNormalizedGTE(v string) predicate.Registration {
	return predicate.Registration(sql.FieldGTE(FieldNameNormalized, v))
}

// NameNormalizedLT applies the LT predicate on the "name_normalized" field.
func NameNormalizedLT(v string) predicate.Registration {
	return predicate.Registration(sql.FieldLT(FieldNameNormalized, v))
}

// NameNormalizedLTE applies the LTE predicate on the "name_normalized" field.
func NameNormalizedLTE(v string) predicate.Registration {
	return predicate.Registration(sql.FieldLTE(FieldNameNormalized, v))
}

// NameNormalizedContains applies the Contains predicate on the "name_normalized" field.
func NameNormalizedContains(v string) predicate.Registration {
	return predicate.Registration(sql.FieldContains(FieldNameNormalized, v))
}

// NameNormalizedHasPrefix applies the HasPrefix predicate on the "name_normalized" field.
func NameNormalizedHasPrefix(v string) predicate.Registration {
	return predicate.Registration(sql.FieldHasPrefix(FieldNameNormalized, v))
}

// NameNormalizedHasSuffix applies the HasSuffix predicate on the "name_normalized" field.
func NameNormalizedHasSuffix(v string) predicate.Registration {
	return predicate.Registration(sql.FieldHasSuffix(FieldNameNormalized, v))
}

// NameNormalizedEqualFold applies the EqualFold predicate on the "name_normalized" field.
func NameNormalizedEqualFold(v string) predicate.Registration {
	return predicate.Registration(sql.FieldEqualFold(FieldNameNormalized, v))
}

// NameNormalizedContainsFold applies the ContainsFold predicate on the "name_normalized" field.
func NameNormalizedContainsFold(v string) predicate.Registration {
	return predicate.Registration(sql.FieldContainsFold(FieldNameNormalized, v))
}

// SecretHashEQ applies the EQ predicate on the "secret_hash" field.
func SecretHashEQ(v string) predicate.Registration {
	return predicate.Registration(sql.FieldEQ(FieldSecretHash, v))
}

// SecretHashNEQ applies the NEQ predicate on the "secret_hash" field.
func SecretHashNEQ(v string) predicate.Registration {
	return predicate.Registration(sql.FieldNEQ(FieldSecretHash, v))
}

// SecretHashIn applies the In predicate on the "secret_hash" field.
func SecretHashIn(vs ...string) predicate.Registration {
	return predicate.Registration(sql.FieldIn(FieldSecretHash, vs...))
}

// SecretHashNotIn applies the NotIn predicate on the "secret_hash" field.
func SecretHashNotIn(vs ...string) predicate.Registration {
	return predicate.Registration(sql.FieldNotIn(FieldSecretHash, vs...))
}

// SecretHashGT applies the GT predicate on the "secret_hash" field.
func SecretHashGT(v string) predicate.Registration {
	return predicate.Registration(sql.FieldGT(FieldSecretHash, v))
}

// SecretHashGTE applies the GTE predicate on the "secret_hash" field.
func SecretHashGTE(v string) predicate.Registration {
	return predicate.Registration(sql.FieldGTE(FieldSecretHash, v))
}

// SecretHashLT applies the LT predicate on the "secret_hash" field.
func SecretHashLT(v string) predicate.Registration {
	return predicate.Registration(sql.FieldLT(FieldSecretHash, v))
}

// SecretHashLTE applies the LTE predicate on the "secret_hash" field.
func SecretHashLTE(v string) predicate.Registration {
	return predicate.Registration(sql.FieldLTE(FieldSecretHash, v))
}

// SecretHashContains applies the Contains predicate on the "secret_hash" field.
func SecretHashContains(v string) predicate.Registration {
	return predicate.Registration(sql.FieldContains(FieldSecretHash, v))
}

// SecretHashHasPrefix applies the HasPrefix predicate on the "secret_hash" field.
func SecretHashHasPrefix(v string) predicate.Registration {
	return predicate.Registration(sql.FieldHasPrefix(FieldSecretHash, v))
}

// SecretHashHasSuffix applies the HasSuffix predicate on the "secret_hash" field.
func SecretHashHasSuffix(v string) predicate.Registration {
	return predicate.Registration(sql.FieldHasSuffix(FieldSecretHash, v))
}

// SecretHashEqualFold applies the EqualFold predicate on the "secret_hash" field.
func SecretHashEqualFold(v string) predicate.Registration {
	return predicate.Registration(sql.FieldEqualFold(FieldSecretHash, v))
}

// SecretHashContainsFold applies the ContainsFold predicate on the "secret_hash" field.
func SecretHashContainsFold(v string) predicate.Registration {
	return predicate.Registration(sql.FieldContainsFold(FieldSecretHash, v))
}

// ViaSharedDeviceEQ applies the EQ predicate on the "via_shared_device" field.
func ViaSharedDeviceEQ(v bool) predicate.Registration {
	return predicate.Registration(sql.FieldEQ(FieldViaSharedDevice, v))
}

// ViaSharedDeviceNEQ applies the NEQ predicate on the "via_shared_device" field.
func ViaSharedDeviceNEQ(v bool) predicate.Registration {
	return predicate.Registration(sql.FieldNEQ(FieldViaSharedDevice, v))
}

// LeftNeighborIDEQ applies the EQ predicate on the "left_neighbor_id" field.
func LeftNeighborIDEQ(v int) predicate.Registration {
	return predicate.Registration(sql.FieldEQ(FieldLeftNeighborID, v))
}

// LeftNeighborIDNEQ applies the NEQ predicate on the "left_neighbor_id" field.
func LeftNeighborIDNEQ(v int) predicate.Registration {
	return predicate.Registration(sql.FieldNEQ(FieldLeftNeighborID, v))
}

// LeftNeighborIDIn applies the In predicate on the "left_neighbor_id" field.
func LeftNeighborIDIn(vs ...int) predicate.Registration {
	return predicate.Registration(sql.FieldIn(FieldLeftNeighborID, vs...))
}

// LeftNeighborIDNotIn applies the NotIn predicate on the "left_neighbor_id" field.
func LeftNeighborIDNotIn(vs ...int) predicate.Registration {
	return predicate.Registration(sql.FieldNotIn(FieldLeftNeighborID, vs...))
}

// LeftNeighborIDGT applies the GT predicate on the "left_neighbor_id" field.
func LeftNeighborIDGT(v int) predicate.Registration {
	return predicate.Registration(sql.FieldGT(FieldLeftNeighborID, v))
}

// LeftNeighborIDGTE applies the GTE predicate on the "left_neighbor_id" field.
func LeftNeighborIDGTE(v int) predicate.Registration {
	return predicate.Registration(sql.FieldGTE(FieldLeftNeighborID, v))
}

// LeftNeighborIDLT applies the LT predicate on the "left_neighbor_id" field.
func LeftNeighborIDLT(v int) predicate.Registration {
	return predicate.Registration(sql.FieldLT(FieldLeftNeighborID, v))
}

// LeftNeighborIDLTE applies the LTE predicate on the "left_neighbor_id" field.
func LeftNeighborIDLTE(v int) predicate.Registration {
	return predicate.Registration(sql.FieldLTE(FieldLeftNeighborID, v))
}

// LeftNeighborIDIsNil applies the IsNil predicate on the "left_neighbor_id" field.
func LeftNeighborIDIsNil() predicate.Registration {
	return predicate.Registration(sql.FieldIsNull(FieldLeftNeighborID))
}

// LeftNeighborIDNotNil applies the NotNil predicate on the "left_neighbor_id" field.
func LeftNeighborIDNotNil() predicate.Registration {
	return predicate.Registration(sql.FieldNotNull(FieldLeftNeighborID))
}

// RightNeighborIDEQ applies the EQ predicate on the "right_neighbor_id" field.
func RightNeighborIDEQ(v int) predicate.Registration {
	return predicate.Registration(sql.FieldEQ(FieldRightNeighborID, v))
}

// RightNeighborIDNEQ applies the NEQ predicate on the "right_neighbor_id" field.
func RightNeighborIDNEQ(v int) predicate.Registration {
	return predicate.Registration(sql.FieldNEQ(FieldRightNeighborID, v))
}

// RightNeighborIDIn applies the In predicate on the "right_neighbor_id" field.
func RightNeighborIDIn(vs ...int) predicate.Registration {
	return predicate.Registration(sql.FieldIn(FieldRightNeighborID, vs...))
}

// RightNeighborIDNotIn applies the NotIn predicate on the "right_neighbor_id" field.
func RightNeighborIDNotIn(vs ...int) predicate.Registration {
	return predicate.Registration(sql.FieldNotIn(FieldRightNeighborID, vs...))
}

// RightNeighborIDGT applies the GT predicate on the "right_neighbor_id" field.
func RightNeighborIDGT(v int) predicate.Registration {
	return predicate.Registration(sql.FieldGT(FieldRightNeighborID, v))
}

// RightNeighborIDGTE applies the GTE predicate on the "right_neighbor_id" field.
func RightNeighborIDGTE(v int) predicate.Registration {
	return predicate.Registration(sql.FieldGTE(FieldRightNeighborID, v))
}

// RightNeighborIDLT applies the LT predicate on the "right_neighbor_id" field.
func RightNeighborIDLT(v int) predicate.Registration {
	return predicate.Registration(sql.FieldLT(FieldRightNeighborID, v))
}

// RightNeighborIDLTE applies the LTE predicate on the "right_neighbor_id" field.
func RightNeighborIDLTE(v int) predicate.Registration {
	return predicate.Registration(sql.FieldLTE(FieldRightNeighborID, v))
}

// RightNeighborIDIsNil applies the IsNil predicate on the "right_neighbor_id" field.
func RightNeighborIDIsNil() predicate.Registration {
	return predicate.Registration(sql.FieldIsNull(FieldRightNeighborID))
}

// RightNeighborIDNotNil applies the NotNil predicate on the "right_neighbor_id" field.
func RightNeighborIDNotNil() predicate.Registration {
	return predicate.Registration(sql.FieldNotNull(FieldRightNeighborID))
}

// AssignedRoleIDEQ applies the EQ predicate on the "assigned_role_id" field.
func AssignedRoleIDEQ(v string) predicate.Registration {
	return predicate.Registration(sql.FieldEQ(FieldAssignedRoleID, v))
}

// AssignedRoleIDNEQ applies the NEQ predicate on the "assigned_role_id" field.
func AssignedRoleIDNEQ(v string) predicate.Registration {
	return predicate.Registration(sql.FieldNEQ(FieldAssignedRoleID, v))
}

// AssignedRoleIDIn applies the In predicate on the "assigned_role_id" field.
func AssignedRoleIDIn(vs ...string) predicate.Registration {
	return predicate.Registration(sql.FieldIn(FieldAssignedRoleID, vs...))
}

// AssignedRoleIDNotIn applies the NotIn predicate on the "assigned_role_id" field.
func AssignedRoleIDNotIn(vs ...string) predicate.Registration {
	return predicate.Registration(sql.FieldNotIn(FieldAssignedRoleID, vs...))
}

// AssignedRoleIDGT applies the GT predicate on the "assigned_role_id" field.
func AssignedRoleIDGT(v string) predicate.Registration {
	return predicate.Registration(sql.FieldGT(FieldAssignedRoleID, v))
}

// AssignedRoleIDGTE applies the GTE predicate on the "assigned_role_id" field.
func AssignedRoleIDGTE(v string) predicate.Registration {
	return predicate.Registration(sql.FieldGTE(FieldAssignedRoleID, v))
}

// AssignedRoleIDLT applies the LT predicate on the "assigned_role_id" field.
func AssignedRoleIDLT(v string) predicate.Registration {
	return predicate.Registration(sql.FieldLT(FieldAssignedRoleID, v))
}

// AssignedRoleIDLTE applies the LTE predicate on the "assigned_role_id" field.
func AssignedRoleIDLTE(v string) predicate.Registration {
	return predicate.Registration(sql.FieldLTE(FieldAssignedRoleID, v))
}

// AssignedRoleIDContains applies the Contains predicate on the "assigned_role_id" field.
func AssignedRoleIDContains(v string) predicate.Registration {
	return predicate.Registration(sql.FieldContains(FieldAssignedRoleID, v))
}

// AssignedRoleIDHasPrefix applies the HasPrefix predicate on the "assigned_role_id" field.
func AssignedRoleIDHasPrefix(v string) predicate.Registration {
	return predicate.Registration(sql.FieldHasPrefix(FieldAssignedRoleID, v))
}

// AssignedRoleIDHasSuffix applies the HasSuffix predicate on the "assigned_role_id" field.
func AssignedRoleIDHasSuffix(v string) predicate.Registration {
	return predicate.Registration(sql.FieldHasSuffix(FieldAssignedRoleID, v))
}

// AssignedRoleIDIsNil applies the IsNil predicate on the "assigned_role_id" field.
func AssignedRoleIDIsNil() predicate.Registration {
	return predicate.Registration(sql.FieldIsNull(FieldAssignedRoleID))
}

// AssignedRoleIDNotNil applies the NotNil predicate on the "assigned_role_id" field.
func AssignedRoleIDNotNil() predicate.Registration {
	return predicate.Registration(sql.FieldNotNull(FieldAssignedRoleID))
}

// AssignedRoleIDEqualFold applies the EqualFold predicate on the "assigned_role_id" field.
func AssignedRoleIDEqualFold(v string) predicate.Registration {
	return predicate.Registration(sql.FieldEqualFold(FieldAssignedRoleID, v))
}

// AssignedRoleIDContainsFold applies the ContainsFold predicate on the "assigned_role_id" field.
func AssignedRoleIDContainsFold(v string) predicate.Registration {
	return predicate.Registration(sql.FieldContainsFold(FieldAssignedRoleID, v))
}

// HasGame applies the HasEdge predicate on the "game" edge.
func HasGame() predicate.Registration {
	return predicate.Registration(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GameTable, GameColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGameWith applies the HasEdge predicate on the "game" edge with a given conditions (other predicates).
func HasGameWith(preds ...predicate.Game) predicate.Registration {
	return predicate.Registration(func(s *sql.Selector) {
		step := newGameStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Registration) predicate.Registration {
	return predicate.Registration(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Registration) predicate.Registration {
	return predicate.Registration(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Registration) predicate.Registration {
	return predicate.Registration(sql.NotPredicates(p))
}
