// Code generated by ent, DO NOT EDIT.

package death

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the death type in the database.
	Label = "death"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldPhaseID holds the string denoting the phase_id field in the database.
	FieldPhaseID = "phase_id"
	// FieldRoleID holds the string denoting the role_id field in the database.
	FieldRoleID = "role_id"
	// FieldGhostVote holds the string denoting the ghost_vote field in the database.
	FieldGhostVote = "ghost_vote"
	// EdgePhase holds the string denoting the phase edge name in mutations.
	EdgePhase = "phase"
	// Table holds the table name of the death in the database.
	Table = "deaths"
	// PhaseTable is the table that holds the phase relation/edge.
	PhaseTable = "deaths"
	// PhaseInverseTable is the table name for the Phase entity.
	// It exists in this package in order to avoid circular dependency with the "phase" package.
	PhaseInverseTable = "phases"
	// PhaseColumn is the table column denoting the phase relation/edge.
	PhaseColumn = "phase_id"
)

// Columns holds all SQL columns for death fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldPhaseID,
	FieldRoleID,
	FieldGhostVote,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// RoleIDValidator is a validator for the "role_id" field. It is called by the builders before save.
	RoleIDValidator func(string) error
	// DefaultGhostVote holds the default value on creation for the "ghost_vote" field.
	DefaultGhostVote bool
)

// OrderOption defines the ordering options for the Death queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPhaseID orders the results by the phase_id field.
func ByPhaseID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhaseID, opts...).ToFunc()
}

// ByRoleID orders the results by the role_id field.
func ByRoleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRoleID, opts...).ToFunc()
}

// ByGhostVote orders the results by the ghost_vote field.
func ByGhostVote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGhostVote, opts...).ToFunc()
}

// ByPhaseField orders the results by phase field.
func ByPhaseField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPhaseStep(), sql.OrderByField(field, opts...))
	}
}
func newPhaseStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PhaseInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PhaseTable, PhaseColumn),
	)
}
