// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/loomi-labs/clockkeeper/ent/infocard"
	"github.com/loomi-labs/clockkeeper/ent/predicate"
	"github.com/loomi-labs/clockkeeper/ent/user"
)

// InfoCardUpdate is the builder for updating InfoCard entities.
type InfoCardUpdate struct {
	config
	hooks    []Hook
	mutation *InfoCardMutation
}

// Where appends a list predicates to the InfoCardUpdate builder.
func (_u *InfoCardUpdate) Where(ps ...predicate.InfoCard) *InfoCardUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InfoCardUpdate) SetUpdatedAt(v time.Time) *InfoCardUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *InfoCardUpdate) SetTitle(v string) *InfoCardUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *InfoCardUpdate) SetNillableTitle(v *string) *InfoCardUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *InfoCardUpdate) SetBody(v string) *InfoCardUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *InfoCardUpdate) SetNillableBody(v *string) *InfoCardUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetCharacterIds sets the "character_ids" field.
func (_u *InfoCardUpdate) SetCharacterIds(v []string) *InfoCardUpdate {
	_u.mutation.SetCharacterIds(v)
	return _u
}

// AppendCharacterIds appends value to the "character_ids" field.
func (_u *InfoCardUpdate) AppendCharacterIds(v []string) *InfoCardUpdate {
	_u.mutation.AppendCharacterIds(v)
	return _u
}

// ClearCharacterIds clears the value of the "character_ids" field.
func (_u *InfoCardUpdate) ClearCharacterIds() *InfoCardUpdate {
	_u.mutation.ClearCharacterIds()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *InfoCardUpdate) SetUserID(v int) *InfoCardUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *InfoCardUpdate) SetNillableUserID(v *int) *InfoCardUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *InfoCardUpdate) SetSortOrder(v int) *InfoCardUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *InfoCardUpdate) SetNillableSortOrder(v *int) *InfoCardUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *InfoCardUpdate) AddSortOrder(v int) *InfoCardUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *InfoCardUpdate) SetOwnerID(id int) *InfoCardUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *InfoCardUpdate) SetOwner(v *User) *InfoCardUpdate {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the InfoCardMutation object of the builder.
func (_u *InfoCardUpdate) Mutation() *InfoCardMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *InfoCardUpdate) ClearOwner() *InfoCardUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InfoCardUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InfoCardUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InfoCardUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InfoCardUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InfoCardUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := infocard.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InfoCardUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := infocard.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "InfoCard.title": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InfoCard.owner"`)
	}
	return nil
}

func (_u *InfoCardUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(infocard.Table, infocard.Columns, sqlgraph.NewFieldSpec(infocard.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(infocard.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(infocard.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(infocard.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.CharacterIds(); ok {
		_spec.SetField(infocard.FieldCharacterIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCharacterIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, infocard.FieldCharacterIds, value)
		})
	}
	if _u.mutation.CharacterIdsCleared() {
		_spec.ClearField(infocard.FieldCharacterIds, field.TypeJSON)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(infocard.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(infocard.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   infocard.OwnerTable,
			Columns: []string{infocard.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   infocard.OwnerTable,
			Columns: []string{infocard.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{infocard.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InfoCardUpdateOne is the builder for updating a single InfoCard entity.
type InfoCardUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InfoCardMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InfoCardUpdateOne) SetUpdatedAt(v time.Time) *InfoCardUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *InfoCardUpdateOne) SetTitle(v string) *InfoCardUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *InfoCardUpdateOne) SetNillableTitle(v *string) *InfoCardUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *InfoCardUpdateOne) SetBody(v string) *InfoCardUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *InfoCardUpdateOne) SetNillableBody(v *string) *InfoCardUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetCharacterIds sets the "character_ids" field.
func (_u *InfoCardUpdateOne) SetCharacterIds(v []string) *InfoCardUpdateOne {
	_u.mutation.SetCharacterIds(v)
	return _u
}

// AppendCharacterIds appends value to the "character_ids" field.
func (_u *InfoCardUpdateOne) AppendCharacterIds(v []string) *InfoCardUpdateOne {
	_u.mutation.AppendCharacterIds(v)
	return _u
}

// ClearCharacterIds clears the value of the "character_ids" field.
func (_u *InfoCardUpdateOne) ClearCharacterIds() *InfoCardUpdateOne {
	_u.mutation.ClearCharacterIds()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *InfoCardUpdateOne) SetUserID(v int) *InfoCardUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *InfoCardUpdateOne) SetNillableUserID(v *int) *InfoCardUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *InfoCardUpdateOne) SetSortOrder(v int) *InfoCardUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *InfoCardUpdateOne) SetNillableSortOrder(v *int) *InfoCardUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *InfoCardUpdateOne) AddSortOrder(v int) *InfoCardUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *InfoCardUpdateOne) SetOwnerID(id int) *InfoCardUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *InfoCardUpdateOne) SetOwner(v *User) *InfoCardUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the InfoCardMutation object of the builder.
func (_u *InfoCardUpdateOne) Mutation() *InfoCardMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *InfoCardUpdateOne) ClearOwner() *InfoCardUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// Where appends a list predicates to the InfoCardUpdate builder.
func (_u *InfoCardUpdateOne) Where(ps ...predicate.InfoCard) *InfoCardUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InfoCardUpdateOne) Select(field string, fields ...string) *InfoCardUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InfoCard entity.
func (_u *InfoCardUpdateOne) Save(ctx context.Context) (*InfoCard, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InfoCardUpdateOne) SaveX(ctx context.Context) *InfoCard {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InfoCardUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InfoCardUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InfoCardUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := infocard.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InfoCardUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := infocard.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "InfoCard.title": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InfoCard.owner"`)
	}
	return nil
}

func (_u *InfoCardUpdateOne) sqlSave(ctx context.Context) (_node *InfoCard, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(infocard.Table, infocard.Columns, sqlgraph.NewFieldSpec(infocard.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InfoCard.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, infocard.FieldID)
		for _, f := range fields {
			if !infocard.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != infocard.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(infocard.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(infocard.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(infocard.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.CharacterIds(); ok {
		_spec.SetField(infocard.FieldCharacterIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCharacterIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, infocard.FieldCharacterIds, value)
		})
	}
	if _u.mutation.CharacterIdsCleared() {
		_spec.ClearField(infocard.FieldCharacterIds, field.TypeJSON)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(infocard.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(infocard.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   infocard.OwnerTable,
			Columns: []string{infocard.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   infocard.OwnerTable,
			Columns: []string{infocard.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &InfoCard{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{infocard.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
