// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/loomi-labs/clockkeeper/ent/infocard"
	"github.com/loomi-labs/clockkeeper/ent/user"
)

// InfoCardCreate is the builder for creating a InfoCard entity.
type InfoCardCreate struct {
	config
	mutation *InfoCardMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *InfoCardCreate) SetCreatedAt(v time.Time) *InfoCardCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InfoCardCreate) SetNillableCreatedAt(v *time.Time) *InfoCardCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *InfoCardCreate) SetUpdatedAt(v time.Time) *InfoCardCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *InfoCardCreate) SetNillableUpdatedAt(v *time.Time) *InfoCardCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *InfoCardCreate) SetTitle(v string) *InfoCardCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetBody sets the "body" field.
func (_c *InfoCardCreate) SetBody(v string) *InfoCardCreate {
	_c.mutation.SetBody(v)
	return _c
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_c *InfoCardCreate) SetNillableBody(v *string) *InfoCardCreate {
	if v != nil {
		_c.SetBody(*v)
	}
	return _c
}

// SetCharacterIds sets the "character_ids" field.
func (_c *InfoCardCreate) SetCharacterIds(v []string) *InfoCardCreate {
	_c.mutation.SetCharacterIds(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *InfoCardCreate) SetUserID(v int) *InfoCardCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *InfoCardCreate) SetSortOrder(v int) *InfoCardCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *InfoCardCreate) SetNillableSortOrder(v *int) *InfoCardCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_c *InfoCardCreate) SetOwnerID(id int) *InfoCardCreate {
	_c.mutation.SetOwnerID(id)
	return _c
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *InfoCardCreate) SetOwner(v *User) *InfoCardCreate {
	return _c.SetOwnerID(v.ID)
}

// Mutation returns the InfoCardMutation object of the builder.
func (_c *InfoCardCreate) Mutation() *InfoCardMutation {
	return _c.mutation
}

// Save creates the InfoCard in the database.
func (_c *InfoCardCreate) Save(ctx context.Context) (*InfoCard, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InfoCardCreate) SaveX(ctx context.Context) *InfoCard {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InfoCardCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InfoCardCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InfoCardCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := infocard.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := infocard.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Body(); !ok {
		v := infocard.DefaultBody
		_c.mutation.SetBody(v)
	}
	if _, ok := _c.mutation.CharacterIds(); !ok {
		v := infocard.DefaultCharacterIds
		_c.mutation.SetCharacterIds(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := infocard.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InfoCardCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InfoCard.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "InfoCard.updated_at"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "InfoCard.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := infocard.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "InfoCard.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Body(); !ok {
		return &ValidationError{Name: "body", err: errors.New(`ent: missing required field "InfoCard.body"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "InfoCard.user_id"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "InfoCard.sort_order"`)}
	}
	if len(_c.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "InfoCard.owner"`)}
	}
	return nil
}

func (_c *InfoCardCreate) sqlSave(ctx context.Context) (*InfoCard, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InfoCardCreate) createSpec() (*InfoCard, *sqlgraph.CreateSpec) {
	var (
		_node = &InfoCard{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(infocard.Table, sqlgraph.NewFieldSpec(infocard.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(infocard.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(infocard.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(infocard.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Body(); ok {
		_spec.SetField(infocard.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := _c.mutation.CharacterIds(); ok {
		_spec.SetField(infocard.FieldCharacterIds, field.TypeJSON, value)
		_node.CharacterIds = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(infocard.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   infocard.OwnerTable,
			Columns: []string{infocard.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// InfoCardCreateBulk is the builder for creating many InfoCard entities in bulk.
type InfoCardCreateBulk struct {
	config
	err      error
	builders []*InfoCardCreate
}

// Save creates the InfoCard entities in the database.
func (_c *InfoCardCreateBulk) Save(ctx context.Context) ([]*InfoCard, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InfoCard, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InfoCardMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InfoCardCreateBulk) SaveX(ctx context.Context) []*InfoCard {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InfoCardCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InfoCardCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
