// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/loomi-labs/clockkeeper/ent/game"
	"github.com/loomi-labs/clockkeeper/ent/registration"
)

// Registration is the model entity for the Registration schema.
type Registration struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// GameID holds the value of the "game_id" field.
	GameID int `json:"game_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// NameNormalized holds the value of the "name_normalized" field.
	NameNormalized string `json:"name_normalized,omitempty"`
	// SecretHash holds the value of the "secret_hash" field.
	SecretHash string `json:"-"`
	// ViaSharedDevice holds the value of the "via_shared_device" field.
	ViaSharedDevice bool `json:"via_shared_device,omitempty"`
	// LeftNeighborID holds the value of the "left_neighbor_id" field.
	LeftNeighborID int `json:"left_neighbor_id,omitempty"`
	// RightNeighborID holds the value of the "right_neighbor_id" field.
	RightNeighborID int `json:"right_neighbor_id,omitempty"`
	// AssignedRoleID holds the value of the "assigned_role_id" field.
	AssignedRoleID string `json:"assigned_role_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RegistrationQuery when eager-loading is set.
	Edges        RegistrationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RegistrationEdges holds the relations/edges for other nodes in the graph.
type RegistrationEdges struct {
	// Game holds the value of the game edge.
	Game *Game `json:"game,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// GameOrErr returns the Game value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RegistrationEdges) GameOrErr() (*Game, error) {
	if e.Game != nil {
		return e.Game, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: game.Label}
	}
	return nil, &NotLoadedError{edge: "game"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Registration) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case registration.FieldViaSharedDevice:
			values[i] = new(sql.NullBool)
		case registration.FieldID, registration.FieldGameID, registration.FieldLeftNeighborID, registration.FieldRightNeighborID:
			values[i] = new(sql.NullInt64)
		case registration.FieldName, registration.FieldNameNormalized, registration.FieldSecretHash, registration.FieldAssignedRoleID:
			values[i] = new(sql.NullString)
		case registration.FieldCreatedAt, registration.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Registration fields.
func (_m *Registration) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case registration.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case registration.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case registration.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case registration.FieldGameID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field game_id", values[i])
			} else if value.Valid {
				_m.GameID = int(value.Int64)
			}
		case registration.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case registration.FieldNameNormalized:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name_normalized", values[i])
			} else if value.Valid {
				_m.NameNormalized = value.String
			}
		case registration.FieldSecretHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field secret_hash", values[i])
			} else if value.Valid {
				_m.SecretHash = value.String
			}
		case registration.FieldViaSharedDevice:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field via_shared_device", values[i])
			} else if value.Valid {
				_m.ViaSharedDevice = value.Bool
			}
		case registration.FieldLeftNeighborID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field left_neighbor_id", values[i])
			} else if value.Valid {
				_m.LeftNeighborID = int(value.Int64)
			}
		case registration.FieldRightNeighborID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field right_neighbor_id", values[i])
			} else if value.Valid {
				_m.RightNeighborID = int(value.Int64)
			}
		case registration.FieldAssignedRoleID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field assigned_role_id", values[i])
			} else if value.Valid {
				_m.AssignedRoleID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Registration.
// This includes values selected through modifiers, order, etc.
func (_m *Registration) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGame queries the "game" edge of the Registration entity.
func (_m *Registration) QueryGame() *GameQuery {
	return NewRegistrationClient(_m.config).QueryGame(_m)
}

// Update returns a builder for updating this Registration.
// Note that you need to call Registration.Unwrap() before calling this method if this Registration
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Registration) Update() *RegistrationUpdateOne {
	return NewRegistrationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Registration entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Registration) Unwrap() *Registration {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Registration is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Registration) String() string {
	var builder strings.Builder
	builder.WriteString("Registration(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("game_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GameID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("name_normalized=")
	builder.WriteString(_m.NameNormalized)
	builder.WriteString(", ")
	builder.WriteString("secret_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("via_shared_device=")
	builder.WriteString(fmt.Sprintf("%v", _m.ViaSharedDevice))
	builder.WriteString(", ")
	builder.WriteString("left_neighbor_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.LeftNeighborID))
	builder.WriteString(", ")
	builder.WriteString("right_neighbor_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RightNeighborID))
	builder.WriteString(", ")
	builder.WriteString("assigned_role_id=")
	builder.WriteString(_m.AssignedRoleID)
	builder.WriteByte(')')
	return builder.String()
}

// Registrations is a parsable slice of Registration.
type Registrations []*Registration
