// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/loomi-labs/clockkeeper/ent/game"
	"github.com/loomi-labs/clockkeeper/ent/registration"
)

// RegistrationCreate is the builder for creating a Registration entity.
type RegistrationCreate struct {
	config
	mutation *RegistrationMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *RegistrationCreate) SetCreatedAt(v time.Time) *RegistrationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RegistrationCreate) SetNillableCreatedAt(v *time.Time) *RegistrationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RegistrationCreate) SetUpdatedAt(v time.Time) *RegistrationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RegistrationCreate) SetNillableUpdatedAt(v *time.Time) *RegistrationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetGameID sets the "game_id" field.
func (_c *RegistrationCreate) SetGameID(v int) *RegistrationCreate {
	_c.mutation.SetGameID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *RegistrationCreate) SetName(v string) *RegistrationCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNameNormalized sets the "name_normalized" field.
func (_c *RegistrationCreate) SetNameNormalized(v string) *RegistrationCreate {
	_c.mutation.SetNameNormalized(v)
	return _c
}

// SetSecretHash sets the "secret_hash" field.
func (_c *RegistrationCreate) SetSecretHash(v string) *RegistrationCreate {
	_c.mutation.SetSecretHash(v)
	return _c
}

// SetViaSharedDevice sets the "via_shared_device" field.
func (_c *RegistrationCreate) SetViaSharedDevice(v bool) *RegistrationCreate {
	_c.mutation.SetViaSharedDevice(v)
	return _c
}

// SetNillableViaSharedDevice sets the "via_shared_device" field if the given value is not nil.
func (_c *RegistrationCreate) SetNillableViaSharedDevice(v *bool) *RegistrationCreate {
	if v != nil {
		_c.SetViaSharedDevice(*v)
	}
	return _c
}

// SetLeftNeighborID sets the "left_neighbor_id" field.
func (_c *RegistrationCreate) SetLeftNeighborID(v int) *RegistrationCreate {
	_c.mutation.SetLeftNeighborID(v)
	return _c
}

// SetNillableLeftNeighborID sets the "left_neighbor_id" field if the given value is not nil.
func (_c *RegistrationCreate) SetNillableLeftNeighborID(v *int) *RegistrationCreate {
	if v != nil {
		_c.SetLeftNeighborID(*v)
	}
	return _c
}

// SetRightNeighborID sets the "right_neighbor_id" field.
func (_c *RegistrationCreate) SetRightNeighborID(v int) *RegistrationCreate {
	_c.mutation.SetRightNeighborID(v)
	return _c
}

// SetNillableRightNeighborID sets the "right_neighbor_id" field if the given value is not nil.
func (_c *RegistrationCreate) SetNillableRightNeighborID(v *int) *RegistrationCreate {
	if v != nil {
		_c.SetRightNeighborID(*v)
	}
	return _c
}

// SetAssignedRoleID sets the "assigned_role_id" field.
func (_c *RegistrationCreate) SetAssignedRoleID(v string) *RegistrationCreate {
	_c.mutation.SetAssignedRoleID(v)
	return _c
}

// SetNillableAssignedRoleID sets the "assigned_role_id" field if the given value is not nil.
func (_c *RegistrationCreate) SetNillableAssignedRoleID(v *string) *RegistrationCreate {
	if v != nil {
		_c.SetAssignedRoleID(*v)
	}
	return _c
}

// SetGame sets the "game" edge to the Game entity.
func (_c *RegistrationCreate) SetGame(v *Game) *RegistrationCreate {
	return _c.SetGameID(v.ID)
}

// Mutation returns the RegistrationMutation object of the builder.
func (_c *RegistrationCreate) Mutation() *RegistrationMutation {
	return _c.mutation
}

// Save creates the Registration in the database.
func (_c *RegistrationCreate) Save(ctx context.Context) (*Registration, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RegistrationCreate) SaveX(ctx context.Context) *Registration {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RegistrationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RegistrationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RegistrationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := registration.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := registration.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ViaSharedDevice(); !ok {
		v := registration.DefaultViaSharedDevice
		_c.mutation.SetViaSharedDevice(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RegistrationCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Registration.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Registration.updated_at"`)}
	}
	if _, ok := _c.mutation.GameID(); !ok {
		return &ValidationError{Name: "game_id", err: errors.New(`ent: missing required field "Registration.game_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Registration.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := registration.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Registration.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NameNormalized(); !ok {
		return &ValidationError{Name: "name_normalized", err: errors.New(`ent: missing required field "Registration.name_normalized"`)}
	}
	if v, ok := _c.mutation.NameNormalized(); ok {
		if err := registration.NameNormalizedValidator(v); err != nil {
			return &ValidationError{Name: "name_normalized", err: fmt.Errorf(`ent: validator failed for field "Registration.name_normalized": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SecretHash(); !ok {
		return &ValidationError{Name: "secret_hash", err: errors.New(`ent: missing required field "Registration.secret_hash"`)}
	}
	if v, ok := _c.mutation.SecretHash(); ok {
		if err := registration.SecretHashValidator(v); err != nil {
			return &ValidationError{Name: "secret_hash", err: fmt.Errorf(`ent: validator failed for field "Registration.secret_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ViaSharedDevice(); !ok {
		return &ValidationError{Name: "via_shared_device", err: errors.New(`ent: missing required field "Registration.via_shared_device"`)}
	}
	if len(_c.mutation.GameIDs()) == 0 {
		return &ValidationError{Name: "game", err: errors.New(`ent: missing required edge "Registration.game"`)}
	}
	return nil
}

func (_c *RegistrationCreate) sqlSave(ctx context.Context) (*Registration, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RegistrationCreate) createSpec() (*Registration, *sqlgraph.CreateSpec) {
	var (
		_node = &Registration{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(registration.Table, sqlgraph.NewFieldSpec(registration.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(registration.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(registration.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(registration.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.NameNormalized(); ok {
		_spec.SetField(registration.FieldNameNormalized, field.TypeString, value)
		_node.NameNormalized = value
	}
	if value, ok := _c.mutation.SecretHash(); ok {
		_spec.SetField(registration.FieldSecretHash, field.TypeString, value)
		_node.SecretHash = value
	}
	if value, ok := _c.mutation.ViaSharedDevice(); ok {
		_spec.SetField(registration.FieldViaSharedDevice, field.TypeBool, value)
		_node.ViaSharedDevice = value
	}
	if value, ok := _c.mutation.LeftNeighborID(); ok {
		_spec.SetField(registration.FieldLeftNeighborID, field.TypeInt, value)
		_node.LeftNeighborID = value
	}
	if value, ok := _c.mutation.RightNeighborID(); ok {
		_spec.SetField(registration.FieldRightNeighborID, field.TypeInt, value)
		_node.RightNeighborID = value
	}
	if value, ok := _c.mutation.AssignedRoleID(); ok {
		_spec.SetField(registration.FieldAssignedRoleID, field.TypeString, value)
		_node.AssignedRoleID = value
	}
	if nodes := _c.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   registration.GameTable,
			Columns: []string{registration.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GameID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RegistrationCreateBulk is the builder for creating many Registration entities in bulk.
type RegistrationCreateBulk struct {
	config
	err      error
	builders []*RegistrationCreate
}

// Save creates the Registration entities in the database.
func (_c *RegistrationCreateBulk) Save(ctx context.Context) ([]*Registration, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Registration, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RegistrationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RegistrationCreateBulk) SaveX(ctx context.Context) []*Registration {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RegistrationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RegistrationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
