// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/loomi-labs/clockkeeper/ent/game"
	"github.com/loomi-labs/clockkeeper/ent/predicate"
	"github.com/loomi-labs/clockkeeper/ent/registration"
)

// RegistrationUpdate is the builder for updating Registration entities.
type RegistrationUpdate struct {
	config
	hooks    []Hook
	mutation *RegistrationMutation
}

// Where appends a list predicates to the RegistrationUpdate builder.
func (_u *RegistrationUpdate) Where(ps ...predicate.Registration) *RegistrationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RegistrationUpdate) SetUpdatedAt(v time.Time) *RegistrationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGameID sets the "game_id" field.
func (_u *RegistrationUpdate) SetGameID(v int) *RegistrationUpdate {
	_u.mutation.SetGameID(v)
	return _u
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_u *RegistrationUpdate) SetNillableGameID(v *int) *RegistrationUpdate {
	if v != nil {
		_u.SetGameID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *RegistrationUpdate) SetName(v string) *RegistrationUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RegistrationUpdate) SetNillableName(v *string) *RegistrationUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNameNormalized sets the "name_normalized" field.
func (_u *RegistrationUpdate) SetNameNormalized(v string) *RegistrationUpdate {
	_u.mutation.SetNameNormalized(v)
	return _u
}

// SetNillableNameNormalized sets the "name_normalized" field if the given value is not nil.
func (_u *RegistrationUpdate) SetNillableNameNormalized(v *string) *RegistrationUpdate {
	if v != nil {
		_u.SetNameNormalized(*v)
	}
	return _u
}

// SetSecretHash sets the "secret_hash" field.
func (_u *RegistrationUpdate) SetSecretHash(v string) *RegistrationUpdate {
	_u.mutation.SetSecretHash(v)
	return _u
}

// SetNillableSecretHash sets the "secret_hash" field if the given value is not nil.
func (_u *RegistrationUpdate) SetNillableSecretHash(v *string) *RegistrationUpdate {
	if v != nil {
		_u.SetSecretHash(*v)
	}
	return _u
}

// SetViaSharedDevice sets the "via_shared_device" field.
func (_u *RegistrationUpdate) SetViaSharedDevice(v bool) *RegistrationUpdate {
	_u.mutation.SetViaSharedDevice(v)
	return _u
}

// SetNillableViaSharedDevice sets the "via_shared_device" field if the given value is not nil.
func (_u *RegistrationUpdate) SetNillableViaSharedDevice(v *bool) *RegistrationUpdate {
	if v != nil {
		_u.SetViaSharedDevice(*v)
	}
	return _u
}

// SetLeftNeighborID sets the "left_neighbor_id" field.
func (_u *RegistrationUpdate) SetLeftNeighborID(v int) *RegistrationUpdate {
	_u.mutation.ResetLeftNeighborID()
	_u.mutation.SetLeftNeighborID(v)
	return _u
}

// SetNillableLeftNeighborID sets the "left_neighbor_id" field if the given value is not nil.
func (_u *RegistrationUpdate) SetNillableLeftNeighborID(v *int) *RegistrationUpdate {
	if v != nil {
		_u.SetLeftNeighborID(*v)
	}
	return _u
}

// AddLeftNeighborID adds value to the "left_neighbor_id" field.
func (_u *RegistrationUpdate) AddLeftNeighborID(v int) *RegistrationUpdate {
	_u.mutation.AddLeftNeighborID(v)
	return _u
}

// ClearLeftNeighborID clears the value of the "left_neighbor_id" field.
func (_u *RegistrationUpdate) ClearLeftNeighborID() *RegistrationUpdate {
	_u.mutation.ClearLeftNeighborID()
	return _u
}

// SetRightNeighborID sets the "right_neighbor_id" field.
func (_u *RegistrationUpdate) SetRightNeighborID(v int) *RegistrationUpdate {
	_u.mutation.ResetRightNeighborID()
	_u.mutation.SetRightNeighborID(v)
	return _u
}

// SetNillableRightNeighborID sets the "right_neighbor_id" field if the given value is not nil.
func (_u *RegistrationUpdate) SetNillableRightNeighborID(v *int) *RegistrationUpdate {
	if v != nil {
		_u.SetRightNeighborID(*v)
	}
	return _u
}

// AddRightNeighborID adds value to the "right_neighbor_id" field.
func (_u *RegistrationUpdate) AddRightNeighborID(v int) *RegistrationUpdate {
	_u.mutation.AddRightNeighborID(v)
	return _u
}

// ClearRightNeighborID clears the value of the "right_neighbor_id" field.
func (_u *RegistrationUpdate) ClearRightNeighborID() *RegistrationUpdate {
	_u.mutation.ClearRightNeighborID()
	return _u
}

// SetAssignedRoleID sets the "assigned_role_id" field.
func (_u *RegistrationUpdate) SetAssignedRoleID(v string) *RegistrationUpdate {
	_u.mutation.SetAssignedRoleID(v)
	return _u
}

// SetNillableAssignedRoleID sets the "assigned_role_id" field if the given value is not nil.
func (_u *RegistrationUpdate) SetNillableAssignedRoleID(v *string) *RegistrationUpdate {
	if v != nil {
		_u.SetAssignedRoleID(*v)
	}
	return _u
}

// ClearAssignedRoleID clears the value of the "assigned_role_id" field.
func (_u *RegistrationUpdate) ClearAssignedRoleID() *RegistrationUpdate {
	_u.mutation.ClearAssignedRoleID()
	return _u
}

// SetGame sets the "game" edge to the Game entity.
func (_u *RegistrationUpdate) SetGame(v *Game) *RegistrationUpdate {
	return _u.SetGameID(v.ID)
}

// Mutation returns the RegistrationMutation object of the builder.
func (_u *RegistrationUpdate) Mutation() *RegistrationMutation {
	return _u.mutation
}

// ClearGame clears the "game" edge to the Game entity.
func (_u *RegistrationUpdate) ClearGame() *RegistrationUpdate {
	_u.mutation.ClearGame()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RegistrationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RegistrationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RegistrationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RegistrationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RegistrationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := registration.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RegistrationUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := registration.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Registration.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NameNormalized(); ok {
		if err := registration.NameNormalizedValidator(v); err != nil {
			return &ValidationError{Name: "name_normalized", err: fmt.Errorf(`ent: validator failed for field "Registration.name_normalized": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SecretHash(); ok {
		if err := registration.SecretHashValidator(v); err != nil {
			return &ValidationError{Name: "secret_hash", err: fmt.Errorf(`ent: validator failed for field "Registration.secret_hash": %w`, err)}
		}
	}
	if _u.mutation.GameCleared() && len(_u.mutation.GameIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Registration.game"`)
	}
	return nil
}

func (_u *RegistrationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(registration.Table, registration.Columns, sqlgraph.NewFieldSpec(registration.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(registration.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(registration.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.NameNormalized(); ok {
		_spec.SetField(registration.FieldNameNormalized, field.TypeString, value)
	}
	if value, ok := _u.mutation.SecretHash(); ok {
		_spec.SetField(registration.FieldSecretHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ViaSharedDevice(); ok {
		_spec.SetField(registration.FieldViaSharedDevice, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LeftNeighborID(); ok {
		_spec.SetField(registration.FieldLeftNeighborID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLeftNeighborID(); ok {
		_spec.AddField(registration.FieldLeftNeighborID, field.TypeInt, value)
	}
	if _u.mutation.LeftNeighborIDCleared() {
		_spec.ClearField(registration.FieldLeftNeighborID, field.TypeInt)
	}
	if value, ok := _u.mutation.RightNeighborID(); ok {
		_spec.SetField(registration.FieldRightNeighborID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRightNeighborID(); ok {
		_spec.AddField(registration.FieldRightNeighborID, field.TypeInt, value)
	}
	if _u.mutation.RightNeighborIDCleared() {
		_spec.ClearField(registration.FieldRightNeighborID, field.TypeInt)
	}
	if value, ok := _u.mutation.AssignedRoleID(); ok {
		_spec.SetField(registration.FieldAssignedRoleID, field.TypeString, value)
	}
	if _u.mutation.AssignedRoleIDCleared() {
		_spec.ClearField(registration.FieldAssignedRoleID, field.TypeString)
	}
	if _u.mutation.GameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   registration.GameTable,
			Columns: []string{registration.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   registration.GameTable,
			Columns: []string{registration.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{registration.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RegistrationUpdateOne is the builder for updating a single Registration entity.
type RegistrationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RegistrationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RegistrationUpdateOne) SetUpdatedAt(v time.Time) *RegistrationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGameID sets the "game_id" field.
func (_u *RegistrationUpdateOne) SetGameID(v int) *RegistrationUpdateOne {
	_u.mutation.SetGameID(v)
	return _u
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_u *RegistrationUpdateOne) SetNillableGameID(v *int) *RegistrationUpdateOne {
	if v != nil {
		_u.SetGameID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *RegistrationUpdateOne) SetName(v string) *RegistrationUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RegistrationUpdateOne) SetNillableName(v *string) *RegistrationUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNameNormalized sets the "name_normalized" field.
func (_u *RegistrationUpdateOne) SetNameNormalized(v string) *RegistrationUpdateOne {
	_u.mutation.SetNameNormalized(v)
	return _u
}

// SetNillableNameNormalized sets the "name_normalized" field if the given value is not nil.
func (_u *RegistrationUpdateOne) SetNillableNameNormalized(v *string) *RegistrationUpdateOne {
	if v != nil {
		_u.SetNameNormalized(*v)
	}
	return _u
}

// SetSecretHash sets the "secret_hash" field.
func (_u *RegistrationUpdateOne) SetSecretHash(v string) *RegistrationUpdateOne {
	_u.mutation.SetSecretHash(v)
	return _u
}

// SetNillableSecretHash sets the "secret_hash" field if the given value is not nil.
func (_u *RegistrationUpdateOne) SetNillableSecretHash(v *string) *RegistrationUpdateOne {
	if v != nil {
		_u.SetSecretHash(*v)
	}
	return _u
}

// SetViaSharedDevice sets the "via_shared_device" field.
func (_u *RegistrationUpdateOne) SetViaSharedDevice(v bool) *RegistrationUpdateOne {
	_u.mutation.SetViaSharedDevice(v)
	return _u
}

// SetNillableViaSharedDevice sets the "via_shared_device" field if the given value is not nil.
func (_u *RegistrationUpdateOne) SetNillableViaSharedDevice(v *bool) *RegistrationUpdateOne {
	if v != nil {
		_u.SetViaSharedDevice(*v)
	}
	return _u
}

// SetLeftNeighborID sets the "left_neighbor_id" field.
func (_u *RegistrationUpdateOne) SetLeftNeighborID(v int) *RegistrationUpdateOne {
	_u.mutation.ResetLeftNeighborID()
	_u.mutation.SetLeftNeighborID(v)
	return _u
}

// SetNillableLeftNeighborID sets the "left_neighbor_id" field if the given value is not nil.
func (_u *RegistrationUpdateOne) SetNillableLeftNeighborID(v *int) *RegistrationUpdateOne {
	if v != nil {
		_u.SetLeftNeighborID(*v)
	}
	return _u
}

// AddLeftNeighborID adds value to the "left_neighbor_id" field.
func (_u *RegistrationUpdateOne) AddLeftNeighborID(v int) *RegistrationUpdateOne {
	_u.mutation.AddLeftNeighborID(v)
	return _u
}

// ClearLeftNeighborID clears the value of the "left_neighbor_id" field.
func (_u *RegistrationUpdateOne) ClearLeftNeighborID() *RegistrationUpdateOne {
	_u.mutation.ClearLeftNeighborID()
	return _u
}

// SetRightNeighborID sets the "right_neighbor_id" field.
func (_u *RegistrationUpdateOne) SetRightNeighborID(v int) *RegistrationUpdateOne {
	_u.mutation.ResetRightNeighborID()
	_u.mutation.SetRightNeighborID(v)
	return _u
}

// SetNillableRightNeighborID sets the "right_neighbor_id" field if the given value is not nil.
func (_u *RegistrationUpdateOne) SetNillableRightNeighborID(v *int) *RegistrationUpdateOne {
	if v != nil {
		_u.SetRightNeighborID(*v)
	}
	return _u
}

// AddRightNeighborID adds value to the "right_neighbor_id" field.
func (_u *RegistrationUpdateOne) AddRightNeighborID(v int) *RegistrationUpdateOne {
	_u.mutation.AddRightNeighborID(v)
	return _u
}

// ClearRightNeighborID clears the value of the "right_neighbor_id" field.
func (_u *RegistrationUpdateOne) ClearRightNeighborID() *RegistrationUpdateOne {
	_u.mutation.ClearRightNeighborID()
	return _u
}

// SetAssignedRoleID sets the "assigned_role_id" field.
func (_u *RegistrationUpdateOne) SetAssignedRoleID(v string) *RegistrationUpdateOne {
	_u.mutation.SetAssignedRoleID(v)
	return _u
}

// SetNillableAssignedRoleID sets the "assigned_role_id" field if the given value is not nil.
func (_u *RegistrationUpdateOne) SetNillableAssignedRoleID(v *string) *RegistrationUpdateOne {
	if v != nil {
		_u.SetAssignedRoleID(*v)
	}
	return _u
}

// ClearAssignedRoleID clears the value of the "assigned_role_id" field.
func (_u *RegistrationUpdateOne) ClearAssignedRoleID() *RegistrationUpdateOne {
	_u.mutation.ClearAssignedRoleID()
	return _u
}

// SetGame sets the "game" edge to the Game entity.
func (_u *RegistrationUpdateOne) SetGame(v *Game) *RegistrationUpdateOne {
	return _u.SetGameID(v.ID)
}

// Mutation returns the RegistrationMutation object of the builder.
func (_u *RegistrationUpdateOne) Mutation() *RegistrationMutation {
	return _u.mutation
}

// ClearGame clears the "game" edge to the Game entity.
func (_u *RegistrationUpdateOne) ClearGame() *RegistrationUpdateOne {
	_u.mutation.ClearGame()
	return _u
}

// Where appends a list predicates to the RegistrationUpdate builder.
func (_u *RegistrationUpdateOne) Where(ps ...predicate.Registration) *RegistrationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RegistrationUpdateOne) Select(field string, fields ...string) *RegistrationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Registration entity.
func (_u *RegistrationUpdateOne) Save(ctx context.Context) (*Registration, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RegistrationUpdateOne) SaveX(ctx context.Context) *Registration {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RegistrationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RegistrationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RegistrationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := registration.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RegistrationUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := registration.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Registration.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NameNormalized(); ok {
		if err := registration.NameNormalizedValidator(v); err != nil {
			return &ValidationError{Name: "name_normalized", err: fmt.Errorf(`ent: validator failed for field "Registration.name_normalized": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SecretHash(); ok {
		if err := registration.SecretHashValidator(v); err != nil {
			return &ValidationError{Name: "secret_hash", err: fmt.Errorf(`ent: validator failed for field "Registration.secret_hash": %w`, err)}
		}
	}
	if _u.mutation.GameCleared() && len(_u.mutation.GameIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Registration.game"`)
	}
	return nil
}

func (_u *RegistrationUpdateOne) sqlSave(ctx context.Context) (_node *Registration, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(registration.Table, registration.Columns, sqlgraph.NewFieldSpec(registration.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Registration.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, registration.FieldID)
		for _, f := range fields {
			if !registration.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != registration.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(registration.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(registration.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.NameNormalized(); ok {
		_spec.SetField(registration.FieldNameNormalized, field.TypeString, value)
	}
	if value, ok := _u.mutation.SecretHash(); ok {
		_spec.SetField(registration.FieldSecretHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ViaSharedDevice(); ok {
		_spec.SetField(registration.FieldViaSharedDevice, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LeftNeighborID(); ok {
		_spec.SetField(registration.FieldLeftNeighborID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLeftNeighborID(); ok {
		_spec.AddField(registration.FieldLeftNeighborID, field.TypeInt, value)
	}
	if _u.mutation.LeftNeighborIDCleared() {
		_spec.ClearField(registration.FieldLeftNeighborID, field.TypeInt)
	}
	if value, ok := _u.mutation.RightNeighborID(); ok {
		_spec.SetField(registration.FieldRightNeighborID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRightNeighborID(); ok {
		_spec.AddField(registration.FieldRightNeighborID, field.TypeInt, value)
	}
	if _u.mutation.RightNeighborIDCleared() {
		_spec.ClearField(registration.FieldRightNeighborID, field.TypeInt)
	}
	if value, ok := _u.mutation.AssignedRoleID(); ok {
		_spec.SetField(registration.FieldAssignedRoleID, field.TypeString, value)
	}
	if _u.mutation.AssignedRoleIDCleared() {
		_spec.ClearField(registration.FieldAssignedRoleID, field.TypeString)
	}
	if _u.mutation.GameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   registration.GameTable,
			Columns: []string{registration.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   registration.GameTable,
			Columns: []string{registration.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Registration{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{registration.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
