// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/loomi-labs/clockkeeper/ent/schema"
	"github.com/loomi-labs/clockkeeper/ent/spotifyconnection"
	"github.com/loomi-labs/clockkeeper/ent/user"
)

// SpotifyConnectionCreate is the builder for creating a SpotifyConnection entity.
type SpotifyConnectionCreate struct {
	config
	mutation *SpotifyConnectionMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *SpotifyConnectionCreate) SetCreatedAt(v time.Time) *SpotifyConnectionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SpotifyConnectionCreate) SetNillableCreatedAt(v *time.Time) *SpotifyConnectionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SpotifyConnectionCreate) SetUpdatedAt(v time.Time) *SpotifyConnectionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SpotifyConnectionCreate) SetNillableUpdatedAt(v *time.Time) *SpotifyConnectionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetSpotifyUserID sets the "spotify_user_id" field.
func (_c *SpotifyConnectionCreate) SetSpotifyUserID(v string) *SpotifyConnectionCreate {
	_c.mutation.SetSpotifyUserID(v)
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *SpotifyConnectionCreate) SetDisplayName(v string) *SpotifyConnectionCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_c *SpotifyConnectionCreate) SetNillableDisplayName(v *string) *SpotifyConnectionCreate {
	if v != nil {
		_c.SetDisplayName(*v)
	}
	return _c
}

// SetPremium sets the "premium" field.
func (_c *SpotifyConnectionCreate) SetPremium(v bool) *SpotifyConnectionCreate {
	_c.mutation.SetPremium(v)
	return _c
}

// SetNillablePremium sets the "premium" field if the given value is not nil.
func (_c *SpotifyConnectionCreate) SetNillablePremium(v *bool) *SpotifyConnectionCreate {
	if v != nil {
		_c.SetPremium(*v)
	}
	return _c
}

// SetRefreshToken sets the "refresh_token" field.
func (_c *SpotifyConnectionCreate) SetRefreshToken(v string) *SpotifyConnectionCreate {
	_c.mutation.SetRefreshToken(v)
	return _c
}

// SetAccessToken sets the "access_token" field.
func (_c *SpotifyConnectionCreate) SetAccessToken(v string) *SpotifyConnectionCreate {
	_c.mutation.SetAccessToken(v)
	return _c
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (_c *SpotifyConnectionCreate) SetNillableAccessToken(v *string) *SpotifyConnectionCreate {
	if v != nil {
		_c.SetAccessToken(*v)
	}
	return _c
}

// SetAccessTokenExpiresAt sets the "access_token_expires_at" field.
func (_c *SpotifyConnectionCreate) SetAccessTokenExpiresAt(v time.Time) *SpotifyConnectionCreate {
	_c.mutation.SetAccessTokenExpiresAt(v)
	return _c
}

// SetNillableAccessTokenExpiresAt sets the "access_token_expires_at" field if the given value is not nil.
func (_c *SpotifyConnectionCreate) SetNillableAccessTokenExpiresAt(v *time.Time) *SpotifyConnectionCreate {
	if v != nil {
		_c.SetAccessTokenExpiresAt(*v)
	}
	return _c
}

// SetDayPlaylist sets the "day_playlist" field.
func (_c *SpotifyConnectionCreate) SetDayPlaylist(v *schema.SpotifyPlaylistSlot) *SpotifyConnectionCreate {
	_c.mutation.SetDayPlaylist(v)
	return _c
}

// SetNightPlaylist sets the "night_playlist" field.
func (_c *SpotifyConnectionCreate) SetNightPlaylist(v *schema.SpotifyPlaylistSlot) *SpotifyConnectionCreate {
	_c.mutation.SetNightPlaylist(v)
	return _c
}

// SetNominationsPlaylist sets the "nominations_playlist" field.
func (_c *SpotifyConnectionCreate) SetNominationsPlaylist(v *schema.SpotifyPlaylistSlot) *SpotifyConnectionCreate {
	_c.mutation.SetNominationsPlaylist(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *SpotifyConnectionCreate) SetUserID(v int) *SpotifyConnectionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *SpotifyConnectionCreate) SetUser(v *User) *SpotifyConnectionCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the SpotifyConnectionMutation object of the builder.
func (_c *SpotifyConnectionCreate) Mutation() *SpotifyConnectionMutation {
	return _c.mutation
}

// Save creates the SpotifyConnection in the database.
func (_c *SpotifyConnectionCreate) Save(ctx context.Context) (*SpotifyConnection, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SpotifyConnectionCreate) SaveX(ctx context.Context) *SpotifyConnection {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SpotifyConnectionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SpotifyConnectionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SpotifyConnectionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := spotifyconnection.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := spotifyconnection.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Premium(); !ok {
		v := spotifyconnection.DefaultPremium
		_c.mutation.SetPremium(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SpotifyConnectionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SpotifyConnection.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SpotifyConnection.updated_at"`)}
	}
	if _, ok := _c.mutation.SpotifyUserID(); !ok {
		return &ValidationError{Name: "spotify_user_id", err: errors.New(`ent: missing required field "SpotifyConnection.spotify_user_id"`)}
	}
	if v, ok := _c.mutation.SpotifyUserID(); ok {
		if err := spotifyconnection.SpotifyUserIDValidator(v); err != nil {
			return &ValidationError{Name: "spotify_user_id", err: fmt.Errorf(`ent: validator failed for field "SpotifyConnection.spotify_user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Premium(); !ok {
		return &ValidationError{Name: "premium", err: errors.New(`ent: missing required field "SpotifyConnection.premium"`)}
	}
	if _, ok := _c.mutation.RefreshToken(); !ok {
		return &ValidationError{Name: "refresh_token", err: errors.New(`ent: missing required field "SpotifyConnection.refresh_token"`)}
	}
	if v, ok := _c.mutation.RefreshToken(); ok {
		if err := spotifyconnection.RefreshTokenValidator(v); err != nil {
			return &ValidationError{Name: "refresh_token", err: fmt.Errorf(`ent: validator failed for field "SpotifyConnection.refresh_token": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "SpotifyConnection.user_id"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "SpotifyConnection.user"`)}
	}
	return nil
}

func (_c *SpotifyConnectionCreate) sqlSave(ctx context.Context) (*SpotifyConnection, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SpotifyConnectionCreate) createSpec() (*SpotifyConnection, *sqlgraph.CreateSpec) {
	var (
		_node = &SpotifyConnection{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(spotifyconnection.Table, sqlgraph.NewFieldSpec(spotifyconnection.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(spotifyconnection.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(spotifyconnection.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.SpotifyUserID(); ok {
		_spec.SetField(spotifyconnection.FieldSpotifyUserID, field.TypeString, value)
		_node.SpotifyUserID = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(spotifyconnection.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.Premium(); ok {
		_spec.SetField(spotifyconnection.FieldPremium, field.TypeBool, value)
		_node.Premium = value
	}
	if value, ok := _c.mutation.RefreshToken(); ok {
		_spec.SetField(spotifyconnection.FieldRefreshToken, field.TypeString, value)
		_node.RefreshToken = value
	}
	if value, ok := _c.mutation.AccessToken(); ok {
		_spec.SetField(spotifyconnection.FieldAccessToken, field.TypeString, value)
		_node.AccessToken = value
	}
	if value, ok := _c.mutation.AccessTokenExpiresAt(); ok {
		_spec.SetField(spotifyconnection.FieldAccessTokenExpiresAt, field.TypeTime, value)
		_node.AccessTokenExpiresAt = &value
	}
	if value, ok := _c.mutation.DayPlaylist(); ok {
		_spec.SetField(spotifyconnection.FieldDayPlaylist, field.TypeJSON, value)
		_node.DayPlaylist = value
	}
	if value, ok := _c.mutation.NightPlaylist(); ok {
		_spec.SetField(spotifyconnection.FieldNightPlaylist, field.TypeJSON, value)
		_node.NightPlaylist = value
	}
	if value, ok := _c.mutation.NominationsPlaylist(); ok {
		_spec.SetField(spotifyconnection.FieldNominationsPlaylist, field.TypeJSON, value)
		_node.NominationsPlaylist = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   spotifyconnection.UserTable,
			Columns: []string{spotifyconnection.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SpotifyConnectionCreateBulk is the builder for creating many SpotifyConnection entities in bulk.
type SpotifyConnectionCreateBulk struct {
	config
	err      error
	builders []*SpotifyConnectionCreate
}

// Save creates the SpotifyConnection entities in the database.
func (_c *SpotifyConnectionCreateBulk) Save(ctx context.Context) ([]*SpotifyConnection, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SpotifyConnection, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SpotifyConnectionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SpotifyConnectionCreateBulk) SaveX(ctx context.Context) []*SpotifyConnection {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SpotifyConnectionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SpotifyConnectionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
