// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/loomi-labs/clockkeeper/ent/schema"
	"github.com/loomi-labs/clockkeeper/ent/spotifyconnection"
	"github.com/loomi-labs/clockkeeper/ent/user"
)

// SpotifyConnection is the model entity for the SpotifyConnection schema.
type SpotifyConnection struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// SpotifyUserID holds the value of the "spotify_user_id" field.
	SpotifyUserID string `json:"spotify_user_id,omitempty"`
	// DisplayName holds the value of the "display_name" field.
	DisplayName string `json:"display_name,omitempty"`
	// Premium holds the value of the "premium" field.
	Premium bool `json:"premium,omitempty"`
	// RefreshToken holds the value of the "refresh_token" field.
	RefreshToken string `json:"-"`
	// AccessToken holds the value of the "access_token" field.
	AccessToken string `json:"-"`
	// AccessTokenExpiresAt holds the value of the "access_token_expires_at" field.
	AccessTokenExpiresAt *time.Time `json:"access_token_expires_at,omitempty"`
	// DayPlaylist holds the value of the "day_playlist" field.
	DayPlaylist *schema.SpotifyPlaylistSlot `json:"day_playlist,omitempty"`
	// NightPlaylist holds the value of the "night_playlist" field.
	NightPlaylist *schema.SpotifyPlaylistSlot `json:"night_playlist,omitempty"`
	// NominationsPlaylist holds the value of the "nominations_playlist" field.
	NominationsPlaylist *schema.SpotifyPlaylistSlot `json:"nominations_playlist,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SpotifyConnectionQuery when eager-loading is set.
	Edges        SpotifyConnectionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SpotifyConnectionEdges holds the relations/edges for other nodes in the graph.
type SpotifyConnectionEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SpotifyConnectionEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SpotifyConnection) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case spotifyconnection.FieldDayPlaylist, spotifyconnection.FieldNightPlaylist, spotifyconnection.FieldNominationsPlaylist:
			values[i] = new([]byte)
		case spotifyconnection.FieldPremium:
			values[i] = new(sql.NullBool)
		case spotifyconnection.FieldID, spotifyconnection.FieldUserID:
			values[i] = new(sql.NullInt64)
		case spotifyconnection.FieldSpotifyUserID, spotifyconnection.FieldDisplayName, spotifyconnection.FieldRefreshToken, spotifyconnection.FieldAccessToken:
			values[i] = new(sql.NullString)
		case spotifyconnection.FieldCreatedAt, spotifyconnection.FieldUpdatedAt, spotifyconnection.FieldAccessTokenExpiresAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SpotifyConnection fields.
func (_m *SpotifyConnection) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case spotifyconnection.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case spotifyconnection.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case spotifyconnection.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case spotifyconnection.FieldSpotifyUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field spotify_user_id", values[i])
			} else if value.Valid {
				_m.SpotifyUserID = value.String
			}
		case spotifyconnection.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = value.String
			}
		case spotifyconnection.FieldPremium:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field premium", values[i])
			} else if value.Valid {
				_m.Premium = value.Bool
			}
		case spotifyconnection.FieldRefreshToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refresh_token", values[i])
			} else if value.Valid {
				_m.RefreshToken = value.String
			}
		case spotifyconnection.FieldAccessToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_token", values[i])
			} else if value.Valid {
				_m.AccessToken = value.String
			}
		case spotifyconnection.FieldAccessTokenExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field access_token_expires_at", values[i])
			} else if value.Valid {
				_m.AccessTokenExpiresAt = new(time.Time)
				*_m.AccessTokenExpiresAt = value.Time
			}
		case spotifyconnection.FieldDayPlaylist:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field day_playlist", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.DayPlaylist); err != nil {
					return fmt.Errorf("unmarshal field day_playlist: %w", err)
				}
			}
		case spotifyconnection.FieldNightPlaylist:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field night_playlist", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.NightPlaylist); err != nil {
					return fmt.Errorf("unmarshal field night_playlist: %w", err)
				}
			}
		case spotifyconnection.FieldNominationsPlaylist:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field nominations_playlist", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.NominationsPlaylist); err != nil {
					return fmt.Errorf("unmarshal field nominations_playlist: %w", err)
				}
			}
		case spotifyconnection.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SpotifyConnection.
// This includes values selected through modifiers, order, etc.
func (_m *SpotifyConnection) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the SpotifyConnection entity.
func (_m *SpotifyConnection) QueryUser() *UserQuery {
	return NewSpotifyConnectionClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this SpotifyConnection.
// Note that you need to call SpotifyConnection.Unwrap() before calling this method if this SpotifyConnection
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SpotifyConnection) Update() *SpotifyConnectionUpdateOne {
	return NewSpotifyConnectionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SpotifyConnection entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SpotifyConnection) Unwrap() *SpotifyConnection {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SpotifyConnection is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SpotifyConnection) String() string {
	var builder strings.Builder
	builder.WriteString("SpotifyConnection(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("spotify_user_id=")
	builder.WriteString(_m.SpotifyUserID)
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(_m.DisplayName)
	builder.WriteString(", ")
	builder.WriteString("premium=")
	builder.WriteString(fmt.Sprintf("%v", _m.Premium))
	builder.WriteString(", ")
	builder.WriteString("refresh_token=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("access_token=<sensitive>")
	builder.WriteString(", ")
	if v := _m.AccessTokenExpiresAt; v != nil {
		builder.WriteString("access_token_expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("day_playlist=")
	builder.WriteString(fmt.Sprintf("%v", _m.DayPlaylist))
	builder.WriteString(", ")
	builder.WriteString("night_playlist=")
	builder.WriteString(fmt.Sprintf("%v", _m.NightPlaylist))
	builder.WriteString(", ")
	builder.WriteString("nominations_playlist=")
	builder.WriteString(fmt.Sprintf("%v", _m.NominationsPlaylist))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteByte(')')
	return builder.String()
}

// SpotifyConnections is a parsable slice of SpotifyConnection.
type SpotifyConnections []*SpotifyConnection
