// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/loomi-labs/clockkeeper/ent/predicate"
	"github.com/loomi-labs/clockkeeper/ent/spotifyconnection"
)

// SpotifyConnectionDelete is the builder for deleting a SpotifyConnection entity.
type SpotifyConnectionDelete struct {
	config
	hooks    []Hook
	mutation *SpotifyConnectionMutation
}

// Where appends a list predicates to the SpotifyConnectionDelete builder.
func (_d *SpotifyConnectionDelete) Where(ps ...predicate.SpotifyConnection) *SpotifyConnectionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SpotifyConnectionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SpotifyConnectionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SpotifyConnectionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(spotifyconnection.Table, sqlgraph.NewFieldSpec(spotifyconnection.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SpotifyConnectionDeleteOne is the builder for deleting a single SpotifyConnection entity.
type SpotifyConnectionDeleteOne struct {
	_d *SpotifyConnectionDelete
}

// Where appends a list predicates to the SpotifyConnectionDelete builder.
func (_d *SpotifyConnectionDeleteOne) Where(ps ...predicate.SpotifyConnection) *SpotifyConnectionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SpotifyConnectionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{spotifyconnection.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SpotifyConnectionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
