// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/loomi-labs/clockkeeper/ent/predicate"
	"github.com/loomi-labs/clockkeeper/ent/schema"
	"github.com/loomi-labs/clockkeeper/ent/spotifyconnection"
	"github.com/loomi-labs/clockkeeper/ent/user"
)

// SpotifyConnectionUpdate is the builder for updating SpotifyConnection entities.
type SpotifyConnectionUpdate struct {
	config
	hooks    []Hook
	mutation *SpotifyConnectionMutation
}

// Where appends a list predicates to the SpotifyConnectionUpdate builder.
func (_u *SpotifyConnectionUpdate) Where(ps ...predicate.SpotifyConnection) *SpotifyConnectionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SpotifyConnectionUpdate) SetUpdatedAt(v time.Time) *SpotifyConnectionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSpotifyUserID sets the "spotify_user_id" field.
func (_u *SpotifyConnectionUpdate) SetSpotifyUserID(v string) *SpotifyConnectionUpdate {
	_u.mutation.SetSpotifyUserID(v)
	return _u
}

// SetNillableSpotifyUserID sets the "spotify_user_id" field if the given value is not nil.
func (_u *SpotifyConnectionUpdate) SetNillableSpotifyUserID(v *string) *SpotifyConnectionUpdate {
	if v != nil {
		_u.SetSpotifyUserID(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *SpotifyConnectionUpdate) SetDisplayName(v string) *SpotifyConnectionUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *SpotifyConnectionUpdate) SetNillableDisplayName(v *string) *SpotifyConnectionUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// ClearDisplayName clears the value of the "display_name" field.
func (_u *SpotifyConnectionUpdate) ClearDisplayName() *SpotifyConnectionUpdate {
	_u.mutation.ClearDisplayName()
	return _u
}

// SetPremium sets the "premium" field.
func (_u *SpotifyConnectionUpdate) SetPremium(v bool) *SpotifyConnectionUpdate {
	_u.mutation.SetPremium(v)
	return _u
}

// SetNillablePremium sets the "premium" field if the given value is not nil.
func (_u *SpotifyConnectionUpdate) SetNillablePremium(v *bool) *SpotifyConnectionUpdate {
	if v != nil {
		_u.SetPremium(*v)
	}
	return _u
}

// SetRefreshToken sets the "refresh_token" field.
func (_u *SpotifyConnectionUpdate) SetRefreshToken(v string) *SpotifyConnectionUpdate {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_u *SpotifyConnectionUpdate) SetNillableRefreshToken(v *string) *SpotifyConnectionUpdate {
	if v != nil {
		_u.SetRefreshToken(*v)
	}
	return _u
}

// SetAccessToken sets the "access_token" field.
func (_u *SpotifyConnectionUpdate) SetAccessToken(v string) *SpotifyConnectionUpdate {
	_u.mutation.SetAccessToken(v)
	return _u
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (_u *SpotifyConnectionUpdate) SetNillableAccessToken(v *string) *SpotifyConnectionUpdate {
	if v != nil {
		_u.SetAccessToken(*v)
	}
	return _u
}

// ClearAccessToken clears the value of the "access_token" field.
func (_u *SpotifyConnectionUpdate) ClearAccessToken() *SpotifyConnectionUpdate {
	_u.mutation.ClearAccessToken()
	return _u
}

// SetAccessTokenExpiresAt sets the "access_token_expires_at" field.
func (_u *SpotifyConnectionUpdate) SetAccessTokenExpiresAt(v time.Time) *SpotifyConnectionUpdate {
	_u.mutation.SetAccessTokenExpiresAt(v)
	return _u
}

// SetNillableAccessTokenExpiresAt sets the "access_token_expires_at" field if the given value is not nil.
func (_u *SpotifyConnectionUpdate) SetNillableAccessTokenExpiresAt(v *time.Time) *SpotifyConnectionUpdate {
	if v != nil {
		_u.SetAccessTokenExpiresAt(*v)
	}
	return _u
}

// ClearAccessTokenExpiresAt clears the value of the "access_token_expires_at" field.
func (_u *SpotifyConnectionUpdate) ClearAccessTokenExpiresAt() *SpotifyConnectionUpdate {
	_u.mutation.ClearAccessTokenExpiresAt()
	return _u
}

// SetDayPlaylist sets the "day_playlist" field.
func (_u *SpotifyConnectionUpdate) SetDayPlaylist(v *schema.SpotifyPlaylistSlot) *SpotifyConnectionUpdate {
	_u.mutation.SetDayPlaylist(v)
	return _u
}

// ClearDayPlaylist clears the value of the "day_playlist" field.
func (_u *SpotifyConnectionUpdate) ClearDayPlaylist() *SpotifyConnectionUpdate {
	_u.mutation.ClearDayPlaylist()
	return _u
}

// SetNightPlaylist sets the "night_playlist" field.
func (_u *SpotifyConnectionUpdate) SetNightPlaylist(v *schema.SpotifyPlaylistSlot) *SpotifyConnectionUpdate {
	_u.mutation.SetNightPlaylist(v)
	return _u
}

// ClearNightPlaylist clears the value of the "night_playlist" field.
func (_u *SpotifyConnectionUpdate) ClearNightPlaylist() *SpotifyConnectionUpdate {
	_u.mutation.ClearNightPlaylist()
	return _u
}

// SetNominationsPlaylist sets the "nominations_playlist" field.
func (_u *SpotifyConnectionUpdate) SetNominationsPlaylist(v *schema.SpotifyPlaylistSlot) *SpotifyConnectionUpdate {
	_u.mutation.SetNominationsPlaylist(v)
	return _u
}

// ClearNominationsPlaylist clears the value of the "nominations_playlist" field.
func (_u *SpotifyConnectionUpdate) ClearNominationsPlaylist() *SpotifyConnectionUpdate {
	_u.mutation.ClearNominationsPlaylist()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SpotifyConnectionUpdate) SetUserID(v int) *SpotifyConnectionUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SpotifyConnectionUpdate) SetNillableUserID(v *int) *SpotifyConnectionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SpotifyConnectionUpdate) SetUser(v *User) *SpotifyConnectionUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the SpotifyConnectionMutation object of the builder.
func (_u *SpotifyConnectionUpdate) Mutation() *SpotifyConnectionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SpotifyConnectionUpdate) ClearUser() *SpotifyConnectionUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SpotifyConnectionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SpotifyConnectionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SpotifyConnectionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SpotifyConnectionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SpotifyConnectionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := spotifyconnection.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SpotifyConnectionUpdate) check() error {
	if v, ok := _u.mutation.SpotifyUserID(); ok {
		if err := spotifyconnection.SpotifyUserIDValidator(v); err != nil {
			return &ValidationError{Name: "spotify_user_id", err: fmt.Errorf(`ent: validator failed for field "SpotifyConnection.spotify_user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RefreshToken(); ok {
		if err := spotifyconnection.RefreshTokenValidator(v); err != nil {
			return &ValidationError{Name: "refresh_token", err: fmt.Errorf(`ent: validator failed for field "SpotifyConnection.refresh_token": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SpotifyConnection.user"`)
	}
	return nil
}

func (_u *SpotifyConnectionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(spotifyconnection.Table, spotifyconnection.Columns, sqlgraph.NewFieldSpec(spotifyconnection.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(spotifyconnection.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SpotifyUserID(); ok {
		_spec.SetField(spotifyconnection.FieldSpotifyUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(spotifyconnection.FieldDisplayName, field.TypeString, value)
	}
	if _u.mutation.DisplayNameCleared() {
		_spec.ClearField(spotifyconnection.FieldDisplayName, field.TypeString)
	}
	if value, ok := _u.mutation.Premium(); ok {
		_spec.SetField(spotifyconnection.FieldPremium, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(spotifyconnection.FieldRefreshToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessToken(); ok {
		_spec.SetField(spotifyconnection.FieldAccessToken, field.TypeString, value)
	}
	if _u.mutation.AccessTokenCleared() {
		_spec.ClearField(spotifyconnection.FieldAccessToken, field.TypeString)
	}
	if value, ok := _u.mutation.AccessTokenExpiresAt(); ok {
		_spec.SetField(spotifyconnection.FieldAccessTokenExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.AccessTokenExpiresAtCleared() {
		_spec.ClearField(spotifyconnection.FieldAccessTokenExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DayPlaylist(); ok {
		_spec.SetField(spotifyconnection.FieldDayPlaylist, field.TypeJSON, value)
	}
	if _u.mutation.DayPlaylistCleared() {
		_spec.ClearField(spotifyconnection.FieldDayPlaylist, field.TypeJSON)
	}
	if value, ok := _u.mutation.NightPlaylist(); ok {
		_spec.SetField(spotifyconnection.FieldNightPlaylist, field.TypeJSON, value)
	}
	if _u.mutation.NightPlaylistCleared() {
		_spec.ClearField(spotifyconnection.FieldNightPlaylist, field.TypeJSON)
	}
	if value, ok := _u.mutation.NominationsPlaylist(); ok {
		_spec.SetField(spotifyconnection.FieldNominationsPlaylist, field.TypeJSON, value)
	}
	if _u.mutation.NominationsPlaylistCleared() {
		_spec.ClearField(spotifyconnection.FieldNominationsPlaylist, field.TypeJSON)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   spotifyconnection.UserTable,
			Columns: []string{spotifyconnection.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   spotifyconnection.UserTable,
			Columns: []string{spotifyconnection.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{spotifyconnection.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SpotifyConnectionUpdateOne is the builder for updating a single SpotifyConnection entity.
type SpotifyConnectionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SpotifyConnectionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SpotifyConnectionUpdateOne) SetUpdatedAt(v time.Time) *SpotifyConnectionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSpotifyUserID sets the "spotify_user_id" field.
func (_u *SpotifyConnectionUpdateOne) SetSpotifyUserID(v string) *SpotifyConnectionUpdateOne {
	_u.mutation.SetSpotifyUserID(v)
	return _u
}

// SetNillableSpotifyUserID sets the "spotify_user_id" field if the given value is not nil.
func (_u *SpotifyConnectionUpdateOne) SetNillableSpotifyUserID(v *string) *SpotifyConnectionUpdateOne {
	if v != nil {
		_u.SetSpotifyUserID(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *SpotifyConnectionUpdateOne) SetDisplayName(v string) *SpotifyConnectionUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *SpotifyConnectionUpdateOne) SetNillableDisplayName(v *string) *SpotifyConnectionUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// ClearDisplayName clears the value of the "display_name" field.
func (_u *SpotifyConnectionUpdateOne) ClearDisplayName() *SpotifyConnectionUpdateOne {
	_u.mutation.ClearDisplayName()
	return _u
}

// SetPremium sets the "premium" field.
func (_u *SpotifyConnectionUpdateOne) SetPremium(v bool) *SpotifyConnectionUpdateOne {
	_u.mutation.SetPremium(v)
	return _u
}

// SetNillablePremium sets the "premium" field if the given value is not nil.
func (_u *SpotifyConnectionUpdateOne) SetNillablePremium(v *bool) *SpotifyConnectionUpdateOne {
	if v != nil {
		_u.SetPremium(*v)
	}
	return _u
}

// SetRefreshToken sets the "refresh_token" field.
func (_u *SpotifyConnectionUpdateOne) SetRefreshToken(v string) *SpotifyConnectionUpdateOne {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_u *SpotifyConnectionUpdateOne) SetNillableRefreshToken(v *string) *SpotifyConnectionUpdateOne {
	if v != nil {
		_u.SetRefreshToken(*v)
	}
	return _u
}

// SetAccessToken sets the "access_token" field.
func (_u *SpotifyConnectionUpdateOne) SetAccessToken(v string) *SpotifyConnectionUpdateOne {
	_u.mutation.SetAccessToken(v)
	return _u
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (_u *SpotifyConnectionUpdateOne) SetNillableAccessToken(v *string) *SpotifyConnectionUpdateOne {
	if v != nil {
		_u.SetAccessToken(*v)
	}
	return _u
}

// ClearAccessToken clears the value of the "access_token" field.
func (_u *SpotifyConnectionUpdateOne) ClearAccessToken() *SpotifyConnectionUpdateOne {
	_u.mutation.ClearAccessToken()
	return _u
}

// SetAccessTokenExpiresAt sets the "access_token_expires_at" field.
func (_u *SpotifyConnectionUpdateOne) SetAccessTokenExpiresAt(v time.Time) *SpotifyConnectionUpdateOne {
	_u.mutation.SetAccessTokenExpiresAt(v)
	return _u
}

// SetNillableAccessTokenExpiresAt sets the "access_token_expires_at" field if the given value is not nil.
func (_u *SpotifyConnectionUpdateOne) SetNillableAccessTokenExpiresAt(v *time.Time) *SpotifyConnectionUpdateOne {
	if v != nil {
		_u.SetAccessTokenExpiresAt(*v)
	}
	return _u
}

// ClearAccessTokenExpiresAt clears the value of the "access_token_expires_at" field.
func (_u *SpotifyConnectionUpdateOne) ClearAccessTokenExpiresAt() *SpotifyConnectionUpdateOne {
	_u.mutation.ClearAccessTokenExpiresAt()
	return _u
}

// SetDayPlaylist sets the "day_playlist" field.
func (_u *SpotifyConnectionUpdateOne) SetDayPlaylist(v *schema.SpotifyPlaylistSlot) *SpotifyConnectionUpdateOne {
	_u.mutation.SetDayPlaylist(v)
	return _u
}

// ClearDayPlaylist clears the value of the "day_playlist" field.
func (_u *SpotifyConnectionUpdateOne) ClearDayPlaylist() *SpotifyConnectionUpdateOne {
	_u.mutation.ClearDayPlaylist()
	return _u
}

// SetNightPlaylist sets the "night_playlist" field.
func (_u *SpotifyConnectionUpdateOne) SetNightPlaylist(v *schema.SpotifyPlaylistSlot) *SpotifyConnectionUpdateOne {
	_u.mutation.SetNightPlaylist(v)
	return _u
}

// ClearNightPlaylist clears the value of the "night_playlist" field.
func (_u *SpotifyConnectionUpdateOne) ClearNightPlaylist() *SpotifyConnectionUpdateOne {
	_u.mutation.ClearNightPlaylist()
	return _u
}

// SetNominationsPlaylist sets the "nominations_playlist" field.
func (_u *SpotifyConnectionUpdateOne) SetNominationsPlaylist(v *schema.SpotifyPlaylistSlot) *SpotifyConnectionUpdateOne {
	_u.mutation.SetNominationsPlaylist(v)
	return _u
}

// ClearNominationsPlaylist clears the value of the "nominations_playlist" field.
func (_u *SpotifyConnectionUpdateOne) ClearNominationsPlaylist() *SpotifyConnectionUpdateOne {
	_u.mutation.ClearNominationsPlaylist()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SpotifyConnectionUpdateOne) SetUserID(v int) *SpotifyConnectionUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SpotifyConnectionUpdateOne) SetNillableUserID(v *int) *SpotifyConnectionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SpotifyConnectionUpdateOne) SetUser(v *User) *SpotifyConnectionUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the SpotifyConnectionMutation object of the builder.
func (_u *SpotifyConnectionUpdateOne) Mutation() *SpotifyConnectionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SpotifyConnectionUpdateOne) ClearUser() *SpotifyConnectionUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the SpotifyConnectionUpdate builder.
func (_u *SpotifyConnectionUpdateOne) Where(ps ...predicate.SpotifyConnection) *SpotifyConnectionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SpotifyConnectionUpdateOne) Select(field string, fields ...string) *SpotifyConnectionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SpotifyConnection entity.
func (_u *SpotifyConnectionUpdateOne) Save(ctx context.Context) (*SpotifyConnection, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SpotifyConnectionUpdateOne) SaveX(ctx context.Context) *SpotifyConnection {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SpotifyConnectionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SpotifyConnectionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SpotifyConnectionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := spotifyconnection.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SpotifyConnectionUpdateOne) check() error {
	if v, ok := _u.mutation.SpotifyUserID(); ok {
		if err := spotifyconnection.SpotifyUserIDValidator(v); err != nil {
			return &ValidationError{Name: "spotify_user_id", err: fmt.Errorf(`ent: validator failed for field "SpotifyConnection.spotify_user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RefreshToken(); ok {
		if err := spotifyconnection.RefreshTokenValidator(v); err != nil {
			return &ValidationError{Name: "refresh_token", err: fmt.Errorf(`ent: validator failed for field "SpotifyConnection.refresh_token": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SpotifyConnection.user"`)
	}
	return nil
}

func (_u *SpotifyConnectionUpdateOne) sqlSave(ctx context.Context) (_node *SpotifyConnection, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(spotifyconnection.Table, spotifyconnection.Columns, sqlgraph.NewFieldSpec(spotifyconnection.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SpotifyConnection.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, spotifyconnection.FieldID)
		for _, f := range fields {
			if !spotifyconnection.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != spotifyconnection.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(spotifyconnection.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SpotifyUserID(); ok {
		_spec.SetField(spotifyconnection.FieldSpotifyUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(spotifyconnection.FieldDisplayName, field.TypeString, value)
	}
	if _u.mutation.DisplayNameCleared() {
		_spec.ClearField(spotifyconnection.FieldDisplayName, field.TypeString)
	}
	if value, ok := _u.mutation.Premium(); ok {
		_spec.SetField(spotifyconnection.FieldPremium, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(spotifyconnection.FieldRefreshToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessToken(); ok {
		_spec.SetField(spotifyconnection.FieldAccessToken, field.TypeString, value)
	}
	if _u.mutation.AccessTokenCleared() {
		_spec.ClearField(spotifyconnection.FieldAccessToken, field.TypeString)
	}
	if value, ok := _u.mutation.AccessTokenExpiresAt(); ok {
		_spec.SetField(spotifyconnection.FieldAccessTokenExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.AccessTokenExpiresAtCleared() {
		_spec.ClearField(spotifyconnection.FieldAccessTokenExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DayPlaylist(); ok {
		_spec.SetField(spotifyconnection.FieldDayPlaylist, field.TypeJSON, value)
	}
	if _u.mutation.DayPlaylistCleared() {
		_spec.ClearField(spotifyconnection.FieldDayPlaylist, field.TypeJSON)
	}
	if value, ok := _u.mutation.NightPlaylist(); ok {
		_spec.SetField(spotifyconnection.FieldNightPlaylist, field.TypeJSON, value)
	}
	if _u.mutation.NightPlaylistCleared() {
		_spec.ClearField(spotifyconnection.FieldNightPlaylist, field.TypeJSON)
	}
	if value, ok := _u.mutation.NominationsPlaylist(); ok {
		_spec.SetField(spotifyconnection.FieldNominationsPlaylist, field.TypeJSON, value)
	}
	if _u.mutation.NominationsPlaylistCleared() {
		_spec.ClearField(spotifyconnection.FieldNominationsPlaylist, field.TypeJSON)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   spotifyconnection.UserTable,
			Columns: []string{spotifyconnection.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   spotifyconnection.UserTable,
			Columns: []string{spotifyconnection.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SpotifyConnection{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{spotifyconnection.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
