// Code generated by ent, DO NOT EDIT.

package phase

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the phase type in the database.
	Label = "phase"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldGameID holds the string denoting the game_id field in the database.
	FieldGameID = "game_id"
	// FieldRoundNumber holds the string denoting the round_number field in the database.
	FieldRoundNumber = "round_number"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// FieldCompletedActions holds the string denoting the completed_actions field in the database.
	FieldCompletedActions = "completed_actions"
	// EdgeGame holds the string denoting the game edge name in mutations.
	EdgeGame = "game"
	// EdgeDeaths holds the string denoting the deaths edge name in mutations.
	EdgeDeaths = "deaths"
	// Table holds the table name of the phase in the database.
	Table = "phases"
	// GameTable is the table that holds the game relation/edge.
	GameTable = "phases"
	// GameInverseTable is the table name for the Game entity.
	// It exists in this package in order to avoid circular dependency with the "game" package.
	GameInverseTable = "games"
	// GameColumn is the table column denoting the game relation/edge.
	GameColumn = "game_id"
	// DeathsTable is the table that holds the deaths relation/edge.
	DeathsTable = "deaths"
	// DeathsInverseTable is the table name for the Death entity.
	// It exists in this package in order to avoid circular dependency with the "death" package.
	DeathsInverseTable = "deaths"
	// DeathsColumn is the table column denoting the deaths relation/edge.
	DeathsColumn = "phase_id"
)

// Columns holds all SQL columns for phase fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldGameID,
	FieldRoundNumber,
	FieldType,
	FieldIsActive,
	FieldCompletedActions,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// RoundNumberValidator is a validator for the "round_number" field. It is called by the builders before save.
	RoundNumberValidator func(int) error
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
	// DefaultCompletedActions holds the default value on creation for the "completed_actions" field.
	DefaultCompletedActions []string
)

// Type defines the type for the "type" enum field.
type Type string

// Type values.
const (
	TypeNight Type = "night"
	TypeDay   Type = "day"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeNight, TypeDay:
		return nil
	default:
		return fmt.Errorf("phase: invalid enum value for type field: %q", _type)
	}
}

// OrderOption defines the ordering options for the Phase queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByGameID orders the results by the game_id field.
func ByGameID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGameID, opts...).ToFunc()
}

// ByRoundNumber orders the results by the round_number field.
func ByRoundNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRoundNumber, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByGameField orders the results by game field.
func ByGameField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGameStep(), sql.OrderByField(field, opts...))
	}
}

// ByDeathsCount orders the results by deaths count.
func ByDeathsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDeathsStep(), opts...)
	}
}

// ByDeaths orders the results by deaths terms.
func ByDeaths(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDeathsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newGameStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GameInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GameTable, GameColumn),
	)
}
func newDeathsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DeathsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DeathsTable, DeathsColumn),
	)
}
