-- Modify "games" table
ALTER TABLE "games" ADD COLUMN "token_bag_phase" character varying NOT NULL DEFAULT 'inactive', ADD COLUMN "token_bag_join_code" character varying NULL, ADD COLUMN "token_bag_shared_code" character varying NULL;
-- Create index "games_token_bag_join_code_key" to table: "games"
CREATE UNIQUE INDEX "games_token_bag_join_code_key" ON "games" ("token_bag_join_code");
-- Create index "games_token_bag_shared_code_key" to table: "games"
CREATE UNIQUE INDEX "games_token_bag_shared_code_key" ON "games" ("token_bag_shared_code");
-- Create "registrations" table
CREATE TABLE "registrations" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "name" character varying NOT NULL,
  "name_normalized" character varying NOT NULL,
  "secret_hash" character varying NOT NULL,
  "via_shared_device" boolean NOT NULL DEFAULT false,
  "left_neighbor_id" bigint NULL,
  "right_neighbor_id" bigint NULL,
  "assigned_role_id" character varying NULL,
  "game_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "registrations_games_registrations" FOREIGN KEY ("game_id") REFERENCES "games" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "registration_name_normalized_game_id" to table: "registrations"
CREATE UNIQUE INDEX "registration_name_normalized_game_id" ON "registrations" ("name_normalized", "game_id");
-- Create index "registration_secret_hash" to table: "registrations"
CREATE UNIQUE INDEX "registration_secret_hash" ON "registrations" ("secret_hash");
