-- Create "info_cards" table
CREATE TABLE "info_cards" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "title" character varying NOT NULL,
  "body" character varying NOT NULL DEFAULT '',
  "character_ids" jsonb NULL,
  "sort_order" bigint NOT NULL DEFAULT 0,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "info_cards_users_info_cards" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
