-- Create "spotify_connections" table
CREATE TABLE "spotify_connections" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "spotify_user_id" character varying NOT NULL,
  "display_name" character varying NULL,
  "premium" boolean NOT NULL DEFAULT false,
  "refresh_token" character varying NOT NULL,
  "access_token" character varying NULL,
  "access_token_expires_at" timestamptz NULL,
  "day_playlist" jsonb NULL,
  "night_playlist" jsonb NULL,
  "nominations_playlist" jsonb NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "spotify_connections_users_spotify_connection" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "spotify_connections_user_id_key" to table: "spotify_connections"
CREATE UNIQUE INDEX "spotify_connections_user_id_key" ON "spotify_connections" ("user_id");
