-- Modify "scripts" table
-- Atlas auto-dropped this constraint because the Ent schema does not declare it.
-- The ownership check is enforced at the application layer (getOwnedGame).
ALTER TABLE "scripts" DROP CONSTRAINT "chk_script_has_owner";
-- Create "phases" table
CREATE TABLE "phases" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "round_number" bigint NOT NULL,
  "type" character varying NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "game_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "phases_games_phases" FOREIGN KEY ("game_id") REFERENCES "games" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "deaths" table
CREATE TABLE "deaths" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "role_id" character varying NOT NULL,
  "ghost_vote" boolean NOT NULL DEFAULT true,
  "phase_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "deaths_phases_deaths" FOREIGN KEY ("phase_id") REFERENCES "phases" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
