// Code generated by ent, DO NOT EDIT.

package spotifyconnection

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/loomi-labs/clockkeeper/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldEQ(FieldUpdatedAt, v))
}

// SpotifyUserID applies equality check predicate on the "spotify_user_id" field. It's identical to SpotifyUserIDEQ.
func SpotifyUserID(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldEQ(FieldSpotifyUserID, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldEQ(FieldDisplayName, v))
}

// Premium applies equality check predicate on the "premium" field. It's identical to PremiumEQ.
func Premium(v bool) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldEQ(FieldPremium, v))
}

// RefreshToken applies equality check predicate on the "refresh_token" field. It's identical to RefreshTokenEQ.
func RefreshToken(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldEQ(FieldRefreshToken, v))
}

// AccessToken applies equality check predicate on the "access_token" field. It's identical to AccessTokenEQ.
func AccessToken(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldEQ(FieldAccessToken, v))
}

// AccessTokenExpiresAt applies equality check predicate on the "access_token_expires_at" field. It's identical to AccessTokenExpiresAtEQ.
func AccessTokenExpiresAt(v time.Time) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldEQ(FieldAccessTokenExpiresAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldEQ(FieldUserID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldLTE(FieldUpdatedAt, v))
}

// SpotifyUserIDEQ applies the EQ predicate on the "spotify_user_id" field.
func SpotifyUserIDEQ(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldEQ(FieldSpotifyUserID, v))
}

// SpotifyUserIDNEQ applies the NEQ predicate on the "spotify_user_id" field.
func SpotifyUserIDNEQ(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldNEQ(FieldSpotifyUserID, v))
}

// SpotifyUserIDIn applies the In predicate on the "spotify_user_id" field.
func SpotifyUserIDIn(vs ...string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldIn(FieldSpotifyUserID, vs...))
}

// SpotifyUserIDNotIn applies the NotIn predicate on the "spotify_user_id" field.
func SpotifyUserIDNotIn(vs ...string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldNotIn(FieldSpotifyUserID, vs...))
}

// SpotifyUserIDGT applies the GT predicate on the "spotify_user_id" field.
func SpotifyUserIDGT(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldGT(FieldSpotifyUserID, v))
}

// SpotifyUserIDGTE applies the GTE predicate on the "spotify_user_id" field.
func SpotifyUserIDGTE(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldGTE(FieldSpotifyUserID, v))
}

// SpotifyUserIDLT applies the LT predicate on the "spotify_user_id" field.
func SpotifyUserIDLT(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldLT(FieldSpotifyUserID, v))
}

// SpotifyUserIDLTE applies the LTE predicate on the "spotify_user_id" field.
func SpotifyUserIDLTE(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldLTE(FieldSpotifyUserID, v))
}

// SpotifyUserIDContains applies the Contains predicate on the "spotify_user_id" field.
func SpotifyUserIDContains(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldContains(FieldSpotifyUserID, v))
}

// SpotifyUserIDHasPrefix applies the HasPrefix predicate on the "spotify_user_id" field.
func SpotifyUserIDHasPrefix(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldHasPrefix(FieldSpotifyUserID, v))
}

// SpotifyUserIDHasSuffix applies the HasSuffix predicate on the "spotify_user_id" field.
func SpotifyUserIDHasSuffix(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldHasSuffix(FieldSpotifyUserID, v))
}

// SpotifyUserIDEqualFold applies the EqualFold predicate on the "spotify_user_id" field.
func SpotifyUserIDEqualFold(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldEqualFold(FieldSpotifyUserID, v))
}

// SpotifyUserIDContainsFold applies the ContainsFold predicate on the "spotify_user_id" field.
func SpotifyUserIDContainsFold(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldContainsFold(FieldSpotifyUserID, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameIsNil applies the IsNil predicate on the "display_name" field.
func DisplayNameIsNil() predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldIsNull(FieldDisplayName))
}

// DisplayNameNotNil applies the NotNil predicate on the "display_name" field.
func DisplayNameNotNil() predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldNotNull(FieldDisplayName))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldContainsFold(FieldDisplayName, v))
}

// PremiumEQ applies the EQ predicate on the "premium" field.
func PremiumEQ(v bool) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldEQ(FieldPremium, v))
}

// PremiumNEQ applies the NEQ predicate on the "premium" field.
func PremiumNEQ(v bool) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldNEQ(FieldPremium, v))
}

// RefreshTokenEQ applies the EQ predicate on the "refresh_token" field.
func RefreshTokenEQ(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldEQ(FieldRefreshToken, v))
}

// RefreshTokenNEQ applies the NEQ predicate on the "refresh_token" field.
func RefreshTokenNEQ(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldNEQ(FieldRefreshToken, v))
}

// RefreshTokenIn applies the In predicate on the "refresh_token" field.
func RefreshTokenIn(vs ...string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldIn(FieldRefreshToken, vs...))
}

// RefreshTokenNotIn applies the NotIn predicate on the "refresh_token" field.
func RefreshTokenNotIn(vs ...string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldNotIn(FieldRefreshToken, vs...))
}

// RefreshTokenGT applies the GT predicate on the "refresh_token" field.
func RefreshTokenGT(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldGT(FieldRefreshToken, v))
}

// RefreshTokenGTE applies the GTE predicate on the "refresh_token" field.
func RefreshTokenGTE(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldGTE(FieldRefreshToken, v))
}

// RefreshTokenLT applies the LT predicate on the "refresh_token" field.
func RefreshTokenLT(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldLT(FieldRefreshToken, v))
}

// RefreshTokenLTE applies the LTE predicate on the "refresh_token" field.
func RefreshTokenLTE(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldLTE(FieldRefreshToken, v))
}

// RefreshTokenContains applies the Contains predicate on the "refresh_token" field.
func RefreshTokenContains(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldContains(FieldRefreshToken, v))
}

// RefreshTokenHasPrefix applies the HasPrefix predicate on the "refresh_token" field.
func RefreshTokenHasPrefix(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldHasPrefix(FieldRefreshToken, v))
}

// RefreshTokenHasSuffix applies the HasSuffix predicate on the "refresh_token" field.
func RefreshTokenHasSuffix(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldHasSuffix(FieldRefreshToken, v))
}

// RefreshTokenEqualFold applies the EqualFold predicate on the "refresh_token" field.
func RefreshTokenEqualFold(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldEqualFold(FieldRefreshToken, v))
}

// RefreshTokenContainsFold applies the ContainsFold predicate on the "refresh_token" field.
func RefreshTokenContainsFold(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldContainsFold(FieldRefreshToken, v))
}

// AccessTokenEQ applies the EQ predicate on the "access_token" field.
func AccessTokenEQ(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldEQ(FieldAccessToken, v))
}

// AccessTokenNEQ applies the NEQ predicate on the "access_token" field.
func AccessTokenNEQ(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldNEQ(FieldAccessToken, v))
}

// AccessTokenIn applies the In predicate on the "access_token" field.
func AccessTokenIn(vs ...string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldIn(FieldAccessToken, vs...))
}

// AccessTokenNotIn applies the NotIn predicate on the "access_token" field.
func AccessTokenNotIn(vs ...string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldNotIn(FieldAccessToken, vs...))
}

// AccessTokenGT applies the GT predicate on the "access_token" field.
func AccessTokenGT(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldGT(FieldAccessToken, v))
}

// AccessTokenGTE applies the GTE predicate on the "access_token" field.
func AccessTokenGTE(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldGTE(FieldAccessToken, v))
}

// AccessTokenLT applies the LT predicate on the "access_token" field.
func AccessTokenLT(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldLT(FieldAccessToken, v))
}

// AccessTokenLTE applies the LTE predicate on the "access_token" field.
func AccessTokenLTE(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldLTE(FieldAccessToken, v))
}

// AccessTokenContains applies the Contains predicate on the "access_token" field.
func AccessTokenContains(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldContains(FieldAccessToken, v))
}

// AccessTokenHasPrefix applies the HasPrefix predicate on the "access_token" field.
func AccessTokenHasPrefix(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldHasPrefix(FieldAccessToken, v))
}

// AccessTokenHasSuffix applies the HasSuffix predicate on the "access_token" field.
func AccessTokenHasSuffix(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldHasSuffix(FieldAccessToken, v))
}

// AccessTokenIsNil applies the IsNil predicate on the "access_token" field.
func AccessTokenIsNil() predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldIsNull(FieldAccessToken))
}

// AccessTokenNotNil applies the NotNil predicate on the "access_token" field.
func AccessTokenNotNil() predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldNotNull(FieldAccessToken))
}

// AccessTokenEqualFold applies the EqualFold predicate on the "access_token" field.
func AccessTokenEqualFold(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldEqualFold(FieldAccessToken, v))
}

// AccessTokenContainsFold applies the ContainsFold predicate on the "access_token" field.
func AccessTokenContainsFold(v string) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldContainsFold(FieldAccessToken, v))
}

// AccessTokenExpiresAtEQ applies the EQ predicate on the "access_token_expires_at" field.
func AccessTokenExpiresAtEQ(v time.Time) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldEQ(FieldAccessTokenExpiresAt, v))
}

// AccessTokenExpiresAtNEQ applies the NEQ predicate on the "access_token_expires_at" field.
func AccessTokenExpiresAtNEQ(v time.Time) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldNEQ(FieldAccessTokenExpiresAt, v))
}

// AccessTokenExpiresAtIn applies the In predicate on the "access_token_expires_at" field.
func AccessTokenExpiresAtIn(vs ...time.Time) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldIn(FieldAccessTokenExpiresAt, vs...))
}

// AccessTokenExpiresAtNotIn applies the NotIn predicate on the "access_token_expires_at" field.
func AccessTokenExpiresAtNotIn(vs ...time.Time) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldNotIn(FieldAccessTokenExpiresAt, vs...))
}

// AccessTokenExpiresAtGT applies the GT predicate on the "access_token_expires_at" field.
func AccessTokenExpiresAtGT(v time.Time) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldGT(FieldAccessTokenExpiresAt, v))
}

// AccessTokenExpiresAtGTE applies the GTE predicate on the "access_token_expires_at" field.
func AccessTokenExpiresAtGTE(v time.Time) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldGTE(FieldAccessTokenExpiresAt, v))
}

// AccessTokenExpiresAtLT applies the LT predicate on the "access_token_expires_at" field.
func AccessTokenExpiresAtLT(v time.Time) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldLT(FieldAccessTokenExpiresAt, v))
}

// AccessTokenExpiresAtLTE applies the LTE predicate on the "access_token_expires_at" field.
func AccessTokenExpiresAtLTE(v time.Time) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldLTE(FieldAccessTokenExpiresAt, v))
}

// AccessTokenExpiresAtIsNil applies the IsNil predicate on the "access_token_expires_at" field.
func AccessTokenExpiresAtIsNil() predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldIsNull(FieldAccessTokenExpiresAt))
}

// AccessTokenExpiresAtNotNil applies the NotNil predicate on the "access_token_expires_at" field.
func AccessTokenExpiresAtNotNil() predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldNotNull(FieldAccessTokenExpiresAt))
}

// DayPlaylistIsNil applies the IsNil predicate on the "day_playlist" field.
func DayPlaylistIsNil() predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldIsNull(FieldDayPlaylist))
}

// DayPlaylistNotNil applies the NotNil predicate on the "day_playlist" field.
func DayPlaylistNotNil() predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldNotNull(FieldDayPlaylist))
}

// NightPlaylistIsNil applies the IsNil predicate on the "night_playlist" field.
func NightPlaylistIsNil() predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldIsNull(FieldNightPlaylist))
}

// NightPlaylistNotNil applies the NotNil predicate on the "night_playlist" field.
func NightPlaylistNotNil() predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldNotNull(FieldNightPlaylist))
}

// NominationsPlaylistIsNil applies the IsNil predicate on the "nominations_playlist" field.
func NominationsPlaylistIsNil() predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldIsNull(FieldNominationsPlaylist))
}

// NominationsPlaylistNotNil applies the NotNil predicate on the "nominations_playlist" field.
func NominationsPlaylistNotNil() predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldNotNull(FieldNominationsPlaylist))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.FieldNotIn(FieldUserID, vs...))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.SpotifyConnection {
	return predicate.SpotifyConnection(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SpotifyConnection) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SpotifyConnection) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SpotifyConnection) predicate.SpotifyConnection {
	return predicate.SpotifyConnection(sql.NotPredicates(p))
}
